In [ ]:
#Apply Map Transform

In [1]:
import pandas as pd

data = {
    "Name": ["Nitu", "Rahul", "Priya", "Amit", "Sneha", "Nitu"],
    "Age": [24, 28, 26, 31, 29, 24],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [35000, 45000, 40000, 60000, 48000, 35000],
    "City": ["Pune", "Mumbai", "Pune", "Delhi", "Mumbai", "Pune"],
    "Joining_Date": [
        "2024-01-15",
        "2022-06-10",
        "2023-03-20",
        "2019-08-12",
        "2021-11-05",
        "2024-01-15"
    ]
}

df = pd.DataFrame(data)
df

    Name  Age Department  Salary    City Joining_Date
0   Nitu   24         IT   35000    Pune   2024-01-15
1  Rahul   28         HR   45000  Mumbai   2022-06-10
2  Priya   26         IT   40000    Pune   2023-03-20
3   Amit   31    Finance   60000   Delhi   2019-08-12
4  Sneha   29         HR   48000  Mumbai   2021-11-05
5   Nitu   24         IT   35000    Pune   2024-01-15

In [8]:
#Q1. Use apply() to increase every salary by 10%.
df["Salary"] = df["Salary"].apply(lambda x: x * 1.10)
df

    Name  Age Department   Salary    City Joining_Date Salary_Level
0   Nitu   24        NaN  42350.0    Pune   2024-01-15          Low
1  Rahul   28        NaN  54450.0  Mumbai   2022-06-10          Low
2  Priya   26        NaN  48400.0    Pune   2023-03-20          Low
3   Amit   31        NaN  72600.0   Delhi   2019-08-12         High
4  Sneha   29        NaN  58080.0  Mumbai   2021-11-05          Low
5   Nitu   24        NaN  42350.0    Pune   2024-01-15          Low

In [6]:
#Q2. Use apply() to create a new column: Salary > 50000 → "High" Otherwise → "Low"
df["Salary_Level"] = df["Salary"].apply(
    lambda x: "High" if x > 50000 else "Low"
)
df

    Name  Age Department  Salary    City Joining_Date Salary_Level
0   Nitu   24        NaN   35000    Pune   2024-01-15          Low
1  Rahul   28        NaN   45000  Mumbai   2022-06-10          Low
2  Priya   26        NaN   40000    Pune   2023-03-20          Low
3   Amit   31        NaN   60000   Delhi   2019-08-12         High
4  Sneha   29        NaN   48000  Mumbai   2021-11-05          Low
5   Nitu   24        NaN   35000    Pune   2024-01-15          Low

In [4]:
#Q3. Use map() to change: IT → Information Technology HR → Human Resources Finance → Financial Services
df["Department"] = df["Department"].map({
    "IT": "Information Technology",
    "HR": "Human Resources",
    "Finance": "Financial Services"
})
df

    Name  Age Department  Salary    City Joining_Date
0   Nitu   24        NaN   35000    Pune   2024-01-15
1  Rahul   28        NaN   45000  Mumbai   2022-06-10
2  Priya   26        NaN   40000    Pune   2023-03-20
3   Amit   31        NaN   60000   Delhi   2019-08-12
4  Sneha   29        NaN   48000  Mumbai   2021-11-05
5   Nitu   24        NaN   35000    Pune   2024-01-15

In [21]:
#Q4. Use transform() to calculate the average salary.
df["Average_Salary"] = df.groupby(lambda x: True)["Salary"].transform("mean")
df

,Name,Age,Department,Salary,City,Joining_Date,Salary_Level,Average_Salary
0,Nitu,24,NaN,42350.0,Pune,2024-01-15,Low,53038.333333
1,Rahul,28,NaN,54450.0,Mumbai,2022-06-10,Low,53038.333333
2,Priya,26,NaN,48400.0,Pune,2023-03-20,Low,53038.333333
3,Amit,31,NaN,72600.0,Delhi,2019-08-12,High,53038.333333
4,Sneha,29,NaN,58080.0,Mumbai,2021-11-05,Low,53038.333333
5,Nitu,24,NaN,42350.0,Pune,2024-01-15,Low,53038.333333