In [ ]:
#Arithmetic Operations

In [1]:
import pandas as pd

var = pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,0]})

print(var)

   A  B
0  1  6
1  2  7
2  3  8
3  4  9
4  5  0

In [2]:
var["C"] = var["A"]+var["B"]
var

   A  B   C
0  1  6   7
1  2  7   9
2  3  8  11
3  4  9  13
4  5  0   5

In [3]:
var["C"] = var["A"] - var["B"]
var

   A  B  C
0  1  6 -5
1  2  7 -5
2  3  8 -5
3  4  9 -5
4  5  0  5

In [4]:
var["C"] = var["A"] * var["B"]
var

   A  B   C
0  1  6   6
1  2  7  14
2  3  8  24
3  4  9  36
4  5  0   0

In [5]:
var["C"] = var["A"] / var["B"]
var

   A  B         C
0  1  6  0.166667
1  2  7  0.285714
2  3  8  0.375000
3  4  9  0.444444
4  5  0       inf

In [6]:
var["C"] = var["A"] % var["B"]
var

   A  B    C
0  1  6  1.0
1  2  7  2.0
2  3  8  3.0
3  4  9  4.0
4  5  0  NaN

In [7]:
var["C"] = var["A"] // var["B"]
var

   A  B    C
0  1  6  0.0
1  2  7  0.0
2  3  8  0.0
3  4  9  0.0
4  5  0  inf

In [10]:
var1 = pd.DataFrame({"A":[11,12,13,14,15],"B":[26,27,28,29,20]})

print(var1)

    A   B
0  11  26
1  12  27
2  13  28
3  14  29
4  15  20

In [19]:
var1["Python"] = var1["A"] <=32

var1

    A   B  Python  Python_1
0  11  26    True     False
1  12  27    True     False
2  13  28    True     False
3  14  29    True     False
4  15  20    True      True

In [22]:
var1["Python_1"] = var1["B"] >=25

var1

    A   B  Python  Python_1
0  11  26    True      True
1  12  27    True      True
2  13  28    True      True
3  14  29    True      True
4  15  20    True     False