In [ ]:
#Date Time

In [1]:
import pandas as pd

data = {
    "Name": ["Nitu", "Rahul", "Priya", "Amit", "Sneha", "Nitu"],
    "Age": [24, 28, 26, 31, 29, 24],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [35000, 45000, 40000, 60000, 48000, 35000],
    "City": ["Pune", "Mumbai", "Pune", "Delhi", "Mumbai", "Pune"],
    "Joining_Date": [
        "2024-01-15",
        "2022-06-10",
        "2023-03-20",
        "2019-08-12",
        "2021-11-05",
        "2024-01-15"
    ]
}

df = pd.DataFrame(data)
df

    Name  Age Department  Salary    City Joining_Date
0   Nitu   24         IT   35000    Pune   2024-01-15
1  Rahul   28         HR   45000  Mumbai   2022-06-10
2  Priya   26         IT   40000    Pune   2023-03-20
3   Amit   31    Finance   60000   Delhi   2019-08-12
4  Sneha   29         HR   48000  Mumbai   2021-11-05
5   Nitu   24         IT   35000    Pune   2024-01-15

In [17]:
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])
df

,Name,Age,Department,Salary,City,Joining_Date,Joining_Year,Joining_Month,Joining_Day,Working_Years
0,Nitu,24,IT,35000,Pune,2024-01-15,2024,1,15,2
1,Rahul,28,HR,45000,Mumbai,2022-06-10,2022,6,10,4
2,Priya,26,IT,40000,Pune,2023-03-20,2023,3,20,3
3,Amit,31,Finance,60000,Delhi,2019-08-12,2019,8,12,6
4,Sneha,29,HR,48000,Mumbai,2021-11-05,2021,11,5,4
5,Nitu,24,IT,35000,Pune,2024-01-15,2024,1,15,2

In [16]:
#Q1. Extract the joining year.
df["Joining_Year"] = df["Joining_Date"].dt.year
df

,Name,Age,Department,Salary,City,Joining_Date,Joining_Year,Joining_Month,Joining_Day,Working_Years
0,Nitu,24,IT,35000,Pune,2024-01-15,2024,1,15,2
1,Rahul,28,HR,45000,Mumbai,2022-06-10,2022,6,10,4
2,Priya,26,IT,40000,Pune,2023-03-20,2023,3,20,3
3,Amit,31,Finance,60000,Delhi,2019-08-12,2019,8,12,6
4,Sneha,29,HR,48000,Mumbai,2021-11-05,2021,11,5,4
5,Nitu,24,IT,35000,Pune,2024-01-15,2024,1,15,2

In [15]:
#Q2. Extract the joining month.
df["Joining_Month"] = df["Joining_Date"].dt.month
df

,Name,Age,Department,Salary,City,Joining_Date,Joining_Year,Joining_Month,Joining_Day,Working_Years
0,Nitu,24,IT,35000,Pune,2024-01-15,2024,1,15,2
1,Rahul,28,HR,45000,Mumbai,2022-06-10,2022,6,10,4
2,Priya,26,IT,40000,Pune,2023-03-20,2023,3,20,3
3,Amit,31,Finance,60000,Delhi,2019-08-12,2019,8,12,6
4,Sneha,29,HR,48000,Mumbai,2021-11-05,2021,11,5,4
5,Nitu,24,IT,35000,Pune,2024-01-15,2024,1,15,2

In [14]:
#Q3. Extract the joining day.
df["Joining_Day"] = df["Joining_Date"].dt.day
df

,Name,Age,Department,Salary,City,Joining_Date,Joining_Year,Joining_Month,Joining_Day,Working_Years
0,Nitu,24,IT,35000,Pune,2024-01-15,2024,1,15,2
1,Rahul,28,HR,45000,Mumbai,2022-06-10,2022,6,10,4
2,Priya,26,IT,40000,Pune,2023-03-20,2023,3,20,3
3,Amit,31,Finance,60000,Delhi,2019-08-12,2019,8,12,6
4,Sneha,29,HR,48000,Mumbai,2021-11-05,2021,11,5,4
5,Nitu,24,IT,35000,Pune,2024-01-15,2024,1,15,2

In [9]:
#Q4. Find employees who joined after 2022.
df[df["Joining_Date"].dt.year > 2022]

,Name,Age,Department,Salary,City,Joining_Date,Joining_Year,Joining_Month,Joining_Day
0,Nitu,24,IT,35000,Pune,2024-01-15,2024,1,15
2,Priya,26,IT,40000,Pune,2023-03-20,2023,3,20
5,Nitu,24,IT,35000,Pune,2024-01-15,2024,1,15

In [10]:
#Q5. Find employees who joined in 2024.
df[df["Joining_Date"].dt.year == 2024]

,Name,Age,Department,Salary,City,Joining_Date,Joining_Year,Joining_Month,Joining_Day
0,Nitu,24,IT,35000,Pune,2024-01-15,2024,1,15
5,Nitu,24,IT,35000,Pune,2024-01-15,2024,1,15

In [13]:
#Q6. Calculate how many years each employee has been working.
df["Working_Years"] = (
    (pd.Timestamp.today() - df["Joining_Date"]).dt.days / 365.25
).astype(int)
df

,Name,Age,Department,Salary,City,Joining_Date,Joining_Year,Joining_Month,Joining_Day,Working_Years
0,Nitu,24,IT,35000,Pune,2024-01-15,2024,1,15,2
1,Rahul,28,HR,45000,Mumbai,2022-06-10,2022,6,10,4
2,Priya,26,IT,40000,Pune,2023-03-20,2023,3,20,3
3,Amit,31,Finance,60000,Delhi,2019-08-12,2019,8,12,6
4,Sneha,29,HR,48000,Mumbai,2021-11-05,2021,11,5,4
5,Nitu,24,IT,35000,Pune,2024-01-15,2024,1,15,2