In [8]:
import pandas as pd

students = {
    "Name": ["Nitu", "Rahul", "Aman"],
    "Age": [24, 25, 23],
    "City": ["Thane", "Mumbai", "Pune"]
}

df = pd.DataFrame(students)

df

    Name  Age    City
0   Nitu   24   Thane
1  Rahul   25  Mumbai
2   Aman   23    Pune

In [16]:
df = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv")
df

    CustomerID CustomerName  Country        State       City
0         1001   Customer_1  Germany   California     Austin
1         1002   Customer_2       UK   California  Bangalore
2         1003   Customer_3       UK  Maharashtra  Bangalore
3         1004   Customer_4      USA  Maharashtra     Mumbai
4         1005   Customer_5  Germany    Karnataka     Mumbai
5         1006   Customer_6    India        Texas     London
6         1007   Customer_7      USA      Bavaria     Munich
7         1008   Customer_8  Germany        Texas     London
8         1009   Customer_9    India        Texas     Munich
9         1010  Customer_10       UK        Texas     Munich
10        1011  Customer_11       UK        Texas     Austin
11        1012  Customer_12       UK   California     Austin
12        1013  Customer_13      USA  Maharashtra     Munich
13        1014  Customer_14      USA    Karnataka     London
14        1015  Customer_15      USA    Karnataka     London
15        1016  Customer_16    India   California     Mumbai
16        1017  Customer_17      USA        Texas       Pune
17        1018  Customer_18       UK      Bavaria     Austin
18        1019  Customer_19    India   California  Bangalore
19        1020  Customer_20    India        Texas  Bangalore
20        1021  Customer_21  Germany    Karnataka     London
21        1022  Customer_22       UK      Bavaria     Austin
22        1023  Customer_23  Germany      Bavaria  Bangalore
23        1024  Customer_24       UK  Maharashtra     Mumbai
24        1025  Customer_25    India   California     Austin
25        1026  Customer_26  Germany      Bavaria     Austin
26        1027  Customer_27    India    Karnataka     Austin
27        1028  Customer_28       UK       London     Munich
28        1029  Customer_29  Germany   California     London
29        1030  Customer_30    India   California     Munich
30        1031  Customer_31       UK        Texas  Bangalore
31        1032  Customer_32      USA        Texas       Pune
32        1033  Customer_33    India       London     London
33        1034  Customer_34       UK      Bavaria     Munich
34        1035  Customer_35    India       London     Munich
35        1036  Customer_36    India    Karnataka       Pune
36        1037  Customer_37       UK        Texas     Austin
37        1038  Customer_38  Germany      Bavaria  Bangalore
38        1039  Customer_39  Germany   California       Pune
39        1040  Customer_40      USA   California       Pune
40        1041  Customer_41  Germany       London       Pune
41        1042  Customer_42  Germany    Karnataka     Munich
42        1043  Customer_43      USA        Texas     Mumbai
43        1044  Customer_44  Germany      Bavaria     Mumbai
44        1045  Customer_45    India    Karnataka     London
45        1046  Customer_46  Germany        Texas     Mumbai
46        1047  Customer_47      USA   California  Bangalore
47        1048  Customer_48  Germany  Maharashtra  Bangalore
48        1049  Customer_49  Germany   California     London
49        1050  Customer_50       UK   California     Austin

In [17]:
df = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv")
df.head()

   CustomerID CustomerName  Country        State       City
0        1001   Customer_1  Germany   California     Austin
1        1002   Customer_2       UK   California  Bangalore
2        1003   Customer_3       UK  Maharashtra  Bangalore
3        1004   Customer_4      USA  Maharashtra     Mumbai
4        1005   Customer_5  Germany    Karnataka     Mumbai

In [18]:
df = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv")
df.tail()

    CustomerID CustomerName  Country        State       City
45        1046  Customer_46  Germany        Texas     Mumbai
46        1047  Customer_47      USA   California  Bangalore
47        1048  Customer_48  Germany  Maharashtra  Bangalore
48        1049  Customer_49  Germany   California     London
49        1050  Customer_50       UK   California     Austin

In [19]:
df = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv")
df.dtypes

CustomerID      int64
CustomerName      str
Country           str
State             str
City              str
dtype: object

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerID    50 non-null     int64
 1   CustomerName  50 non-null     str
 2   Country       50 non-null     str
 3   State         50 non-null     str
 4   City          50 non-null     str
dtypes: int64(1), str(4)
memory usage: 2.1 KB

In [21]:
df = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv")
df.shape

(50, 5)

In [22]:
df = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv")
df.describe

<bound method NDFrame.describe of     CustomerID CustomerName  Country        State       City
0         1001   Customer_1  Germany   California     Austin
1         1002   Customer_2       UK   California  Bangalore
2         1003   Customer_3       UK  Maharashtra  Bangalore
3         1004   Customer_4      USA  Maharashtra     Mumbai
4         1005   Customer_5  Germany    Karnataka     Mumbai
5         1006   Customer_6    India        Texas     London
6         1007   Customer_7      USA      Bavaria     Munich
7         1008   Customer_8  Germany        Texas     London
8         1009   Customer_9    India        Texas     Munich
9         1010  Customer_10       UK        Texas     Munich
10        1011  Customer_11       UK        Texas     Austin
11        1012  Customer_12       UK   California     Austin
12        1013  Customer_13      USA  Maharashtra     Munich
13        1014  Customer_14      USA    Karnataka     London
14        1015  Customer_15      USA    Karnataka     London
15        1016  Customer_16    India   California     Mumbai
16        1017  Customer_17      USA        Texas       Pune
17        1018  Customer_18       UK      Bavaria     Austin
18        1019  Customer_19    India   California  Bangalore
19        1020  Customer_20    India        Texas  Bangalore
20        1021  Customer_21  Germany    Karnataka     London
21        1022  Customer_22       UK      Bavaria     Austin
22        1023  Customer_23  Germany      Bavaria  Bangalore
23        1024  Customer_24       UK  Maharashtra     Mumbai
24        1025  Customer_25    India   California     Austin
25        1026  Customer_26  Germany      Bavaria     Austin
26        1027  Customer_27    India    Karnataka     Austin
27        1028  Customer_28       UK       London     Munich
28        1029  Customer_29  Germany   California     London
29        1030  Customer_30    India   California     Munich
30        1031  Customer_31       UK        Texas  Bangalore
31        1032  Customer_32      USA        Texas       Pune
32        1033  Customer_33    India       London     London
33        1034  Customer_34       UK      Bavaria     Munich
34        1035  Customer_35    India       London     Munich
35        1036  Customer_36    India    Karnataka       Pune
36        1037  Customer_37       UK        Texas     Austin
37        1038  Customer_38  Germany      Bavaria  Bangalore
38        1039  Customer_39  Germany   California       Pune
39        1040  Customer_40      USA   California       Pune
40        1041  Customer_41  Germany       London       Pune
41        1042  Customer_42  Germany    Karnataka     Munich
42        1043  Customer_43      USA        Texas     Mumbai
43        1044  Customer_44  Germany      Bavaria     Mumbai
44        1045  Customer_45    India    Karnataka     London
45        1046  Customer_46  Germany        Texas     Mumbai
46        1047  Customer_47      USA   California  Bangalore
47        1048  Customer_48  Germany  Maharashtra  Bangalore
48        1049  Customer_49  Germany   California     London
49        1050  Customer_50       UK   California     Austin>

In [23]:
df = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv")
df.columns

Index(['CustomerID', 'CustomerName', 'Country', 'State', 'City'], dtype='str')

In [24]:
df = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv",header=None)
df

             0             1        2            3          4
0   CustomerID  CustomerName  Country        State       City
1         1001    Customer_1  Germany   California     Austin
2         1002    Customer_2       UK   California  Bangalore
3         1003    Customer_3       UK  Maharashtra  Bangalore
4         1004    Customer_4      USA  Maharashtra     Mumbai
5         1005    Customer_5  Germany    Karnataka     Mumbai
6         1006    Customer_6    India        Texas     London
7         1007    Customer_7      USA      Bavaria     Munich
8         1008    Customer_8  Germany        Texas     London
9         1009    Customer_9    India        Texas     Munich
10        1010   Customer_10       UK        Texas     Munich
11        1011   Customer_11       UK        Texas     Austin
12        1012   Customer_12       UK   California     Austin
13        1013   Customer_13      USA  Maharashtra     Munich
14        1014   Customer_14      USA    Karnataka     London
15        1015   Customer_15      USA    Karnataka     London
16        1016   Customer_16    India   California     Mumbai
17        1017   Customer_17      USA        Texas       Pune
18        1018   Customer_18       UK      Bavaria     Austin
19        1019   Customer_19    India   California  Bangalore
20        1020   Customer_20    India        Texas  Bangalore
21        1021   Customer_21  Germany    Karnataka     London
22        1022   Customer_22       UK      Bavaria     Austin
23        1023   Customer_23  Germany      Bavaria  Bangalore
24        1024   Customer_24       UK  Maharashtra     Mumbai
25        1025   Customer_25    India   California     Austin
26        1026   Customer_26  Germany      Bavaria     Austin
27        1027   Customer_27    India    Karnataka     Austin
28        1028   Customer_28       UK       London     Munich
29        1029   Customer_29  Germany   California     London
30        1030   Customer_30    India   California     Munich
31        1031   Customer_31       UK        Texas  Bangalore
32        1032   Customer_32      USA        Texas       Pune
33        1033   Customer_33    India       London     London
34        1034   Customer_34       UK      Bavaria     Munich
35        1035   Customer_35    India       London     Munich
36        1036   Customer_36    India    Karnataka       Pune
37        1037   Customer_37       UK        Texas     Austin
38        1038   Customer_38  Germany      Bavaria  Bangalore
39        1039   Customer_39  Germany   California       Pune
40        1040   Customer_40      USA   California       Pune
41        1041   Customer_41  Germany       London       Pune
42        1042   Customer_42  Germany    Karnataka     Munich
43        1043   Customer_43      USA        Texas     Mumbai
44        1044   Customer_44  Germany      Bavaria     Mumbai
45        1045   Customer_45    India    Karnataka     London
46        1046   Customer_46  Germany        Texas     Mumbai
47        1047   Customer_47      USA   California  Bangalore
48        1048   Customer_48  Germany  Maharashtra  Bangalore
49        1049   Customer_49  Germany   California     London
50        1050   Customer_50       UK   California     Austin

In [25]:
df = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv")
df.columns=["c_id","c_name","c_country","c_state","c_city"]
df

    c_id       c_name c_country      c_state     c_city
0   1001   Customer_1   Germany   California     Austin
1   1002   Customer_2        UK   California  Bangalore
2   1003   Customer_3        UK  Maharashtra  Bangalore
3   1004   Customer_4       USA  Maharashtra     Mumbai
4   1005   Customer_5   Germany    Karnataka     Mumbai
5   1006   Customer_6     India        Texas     London
6   1007   Customer_7       USA      Bavaria     Munich
7   1008   Customer_8   Germany        Texas     London
8   1009   Customer_9     India        Texas     Munich
9   1010  Customer_10        UK        Texas     Munich
10  1011  Customer_11        UK        Texas     Austin
11  1012  Customer_12        UK   California     Austin
12  1013  Customer_13       USA  Maharashtra     Munich
13  1014  Customer_14       USA    Karnataka     London
14  1015  Customer_15       USA    Karnataka     London
15  1016  Customer_16     India   California     Mumbai
16  1017  Customer_17       USA        Texas       Pune
17  1018  Customer_18        UK      Bavaria     Austin
18  1019  Customer_19     India   California  Bangalore
19  1020  Customer_20     India        Texas  Bangalore
20  1021  Customer_21   Germany    Karnataka     London
21  1022  Customer_22        UK      Bavaria     Austin
22  1023  Customer_23   Germany      Bavaria  Bangalore
23  1024  Customer_24        UK  Maharashtra     Mumbai
24  1025  Customer_25     India   California     Austin
25  1026  Customer_26   Germany      Bavaria     Austin
26  1027  Customer_27     India    Karnataka     Austin
27  1028  Customer_28        UK       London     Munich
28  1029  Customer_29   Germany   California     London
29  1030  Customer_30     India   California     Munich
30  1031  Customer_31        UK        Texas  Bangalore
31  1032  Customer_32       USA        Texas       Pune
32  1033  Customer_33     India       London     London
33  1034  Customer_34        UK      Bavaria     Munich
34  1035  Customer_35     India       London     Munich
35  1036  Customer_36     India    Karnataka       Pune
36  1037  Customer_37        UK        Texas     Austin
37  1038  Customer_38   Germany      Bavaria  Bangalore
38  1039  Customer_39   Germany   California       Pune
39  1040  Customer_40       USA   California       Pune
40  1041  Customer_41   Germany       London       Pune
41  1042  Customer_42   Germany    Karnataka     Munich
42  1043  Customer_43       USA        Texas     Mumbai
43  1044  Customer_44   Germany      Bavaria     Mumbai
44  1045  Customer_45     India    Karnataka     London
45  1046  Customer_46   Germany        Texas     Mumbai
46  1047  Customer_47       USA   California  Bangalore
47  1048  Customer_48   Germany  Maharashtra  Bangalore
48  1049  Customer_49   Germany   California     London
49  1050  Customer_50        UK   California     Austin

In [28]:
col=["c_id","c_name"]
df[col]

    c_id       c_name
0   1001   Customer_1
1   1002   Customer_2
2   1003   Customer_3
3   1004   Customer_4
4   1005   Customer_5
5   1006   Customer_6
6   1007   Customer_7
7   1008   Customer_8
8   1009   Customer_9
9   1010  Customer_10
10  1011  Customer_11
11  1012  Customer_12
12  1013  Customer_13
13  1014  Customer_14
14  1015  Customer_15
15  1016  Customer_16
16  1017  Customer_17
17  1018  Customer_18
18  1019  Customer_19
19  1020  Customer_20
20  1021  Customer_21
21  1022  Customer_22
22  1023  Customer_23
23  1024  Customer_24
24  1025  Customer_25
25  1026  Customer_26
26  1027  Customer_27
27  1028  Customer_28
28  1029  Customer_29
29  1030  Customer_30
30  1031  Customer_31
31  1032  Customer_32
32  1033  Customer_33
33  1034  Customer_34
34  1035  Customer_35
35  1036  Customer_36
36  1037  Customer_37
37  1038  Customer_38
38  1039  Customer_39
39  1040  Customer_40
40  1041  Customer_41
41  1042  Customer_42
42  1043  Customer_43
43  1044  Customer_44
44  1045  Customer_45
45  1046  Customer_46
46  1047  Customer_47
47  1048  Customer_48
48  1049  Customer_49
49  1050  Customer_50

In [29]:
df[["c_id","c_name"]]

    c_id       c_name
0   1001   Customer_1
1   1002   Customer_2
2   1003   Customer_3
3   1004   Customer_4
4   1005   Customer_5
5   1006   Customer_6
6   1007   Customer_7
7   1008   Customer_8
8   1009   Customer_9
9   1010  Customer_10
10  1011  Customer_11
11  1012  Customer_12
12  1013  Customer_13
13  1014  Customer_14
14  1015  Customer_15
15  1016  Customer_16
16  1017  Customer_17
17  1018  Customer_18
18  1019  Customer_19
19  1020  Customer_20
20  1021  Customer_21
21  1022  Customer_22
22  1023  Customer_23
23  1024  Customer_24
24  1025  Customer_25
25  1026  Customer_26
26  1027  Customer_27
27  1028  Customer_28
28  1029  Customer_29
29  1030  Customer_30
30  1031  Customer_31
31  1032  Customer_32
32  1033  Customer_33
33  1034  Customer_34
34  1035  Customer_35
35  1036  Customer_36
36  1037  Customer_37
37  1038  Customer_38
38  1039  Customer_39
39  1040  Customer_40
40  1041  Customer_41
41  1042  Customer_42
42  1043  Customer_43
43  1044  Customer_44
44  1045  Customer_45
45  1046  Customer_46
46  1047  Customer_47
47  1048  Customer_48
48  1049  Customer_49
49  1050  Customer_50

In [34]:
df_new=df["c_id"]
type(df_new)

pandas.Series