In [ ]:
#Pandas Functions

In [1]:
import pandas as pd

c = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv")

c

    CustomerID CustomerName  Country        State       City
0         1001   Customer_1  Germany   California     Austin
1         1002   Customer_2       UK   California  Bangalore
2         1003   Customer_3       UK  Maharashtra  Bangalore
3         1004   Customer_4      USA  Maharashtra     Mumbai
4         1005   Customer_5  Germany    Karnataka     Mumbai
5         1006   Customer_6    India        Texas     London
6         1007   Customer_7      USA      Bavaria     Munich
7         1008   Customer_8  Germany        Texas     London
8         1009   Customer_9    India        Texas     Munich
9         1010  Customer_10       UK        Texas     Munich
10        1011  Customer_11       UK        Texas     Austin
11        1012  Customer_12       UK   California     Austin
12        1013  Customer_13      USA  Maharashtra     Munich
13        1014  Customer_14      USA    Karnataka     London
14        1015  Customer_15      USA    Karnataka     London
15        1016  Customer_16    India   California     Mumbai
16        1017  Customer_17      USA        Texas       Pune
17        1018  Customer_18       UK      Bavaria     Austin
18        1019  Customer_19    India   California  Bangalore
19        1020  Customer_20    India        Texas  Bangalore
20        1021  Customer_21  Germany    Karnataka     London
21        1022  Customer_22       UK      Bavaria     Austin
22        1023  Customer_23  Germany      Bavaria  Bangalore
23        1024  Customer_24       UK  Maharashtra     Mumbai
24        1025  Customer_25    India   California     Austin
25        1026  Customer_26  Germany      Bavaria     Austin
26        1027  Customer_27    India    Karnataka     Austin
27        1028  Customer_28       UK       London     Munich
28        1029  Customer_29  Germany   California     London
29        1030  Customer_30    India   California     Munich
30        1031  Customer_31       UK        Texas  Bangalore
31        1032  Customer_32      USA        Texas       Pune
32        1033  Customer_33    India       London     London
33        1034  Customer_34       UK      Bavaria     Munich
34        1035  Customer_35    India       London     Munich
35        1036  Customer_36    India    Karnataka       Pune
36        1037  Customer_37       UK        Texas     Austin
37        1038  Customer_38  Germany      Bavaria  Bangalore
38        1039  Customer_39  Germany   California       Pune
39        1040  Customer_40      USA   California       Pune
40        1041  Customer_41  Germany       London       Pune
41        1042  Customer_42  Germany    Karnataka     Munich
42        1043  Customer_43      USA        Texas     Mumbai
43        1044  Customer_44  Germany      Bavaria     Mumbai
44        1045  Customer_45    India    Karnataka     London
45        1046  Customer_46  Germany        Texas     Mumbai
46        1047  Customer_47      USA   California  Bangalore
47        1048  Customer_48  Germany  Maharashtra  Bangalore
48        1049  Customer_49  Germany   California     London
49        1050  Customer_50       UK   California     Austin

In [2]:
c.index

RangeIndex(start=0, stop=50, step=1)

In [3]:
c.columns

Index(['CustomerID', 'CustomerName', 'Country', 'State', 'City'], dtype='str')

In [4]:
c.describe()

       CustomerID
count    50.00000
mean   1025.50000
std      14.57738
min    1001.00000
25%    1013.25000
50%    1025.50000
75%    1037.75000
max    1050.00000

In [5]:
c.head()

   CustomerID CustomerName  Country        State       City
0        1001   Customer_1  Germany   California     Austin
1        1002   Customer_2       UK   California  Bangalore
2        1003   Customer_3       UK  Maharashtra  Bangalore
3        1004   Customer_4      USA  Maharashtra     Mumbai
4        1005   Customer_5  Germany    Karnataka     Mumbai

In [6]:
c.head(2)

   CustomerID CustomerName  Country       State       City
0        1001   Customer_1  Germany  California     Austin
1        1002   Customer_2       UK  California  Bangalore

In [7]:
c.tail()

    CustomerID CustomerName  Country        State       City
45        1046  Customer_46  Germany        Texas     Mumbai
46        1047  Customer_47      USA   California  Bangalore
47        1048  Customer_48  Germany  Maharashtra  Bangalore
48        1049  Customer_49  Germany   California     London
49        1050  Customer_50       UK   California     Austin

In [8]:
c.tail(3)

    CustomerID CustomerName  Country        State       City
47        1048  Customer_48  Germany  Maharashtra  Bangalore
48        1049  Customer_49  Germany   California     London
49        1050  Customer_50       UK   California     Austin

In [9]:
c[3:33]

    CustomerID CustomerName  Country        State       City
3         1004   Customer_4      USA  Maharashtra     Mumbai
4         1005   Customer_5  Germany    Karnataka     Mumbai
5         1006   Customer_6    India        Texas     London
6         1007   Customer_7      USA      Bavaria     Munich
7         1008   Customer_8  Germany        Texas     London
8         1009   Customer_9    India        Texas     Munich
9         1010  Customer_10       UK        Texas     Munich
10        1011  Customer_11       UK        Texas     Austin
11        1012  Customer_12       UK   California     Austin
12        1013  Customer_13      USA  Maharashtra     Munich
13        1014  Customer_14      USA    Karnataka     London
14        1015  Customer_15      USA    Karnataka     London
15        1016  Customer_16    India   California     Mumbai
16        1017  Customer_17      USA        Texas       Pune
17        1018  Customer_18       UK      Bavaria     Austin
18        1019  Customer_19    India   California  Bangalore
19        1020  Customer_20    India        Texas  Bangalore
20        1021  Customer_21  Germany    Karnataka     London
21        1022  Customer_22       UK      Bavaria     Austin
22        1023  Customer_23  Germany      Bavaria  Bangalore
23        1024  Customer_24       UK  Maharashtra     Mumbai
24        1025  Customer_25    India   California     Austin
25        1026  Customer_26  Germany      Bavaria     Austin
26        1027  Customer_27    India    Karnataka     Austin
27        1028  Customer_28       UK       London     Munich
28        1029  Customer_29  Germany   California     London
29        1030  Customer_30    India   California     Munich
30        1031  Customer_31       UK        Texas  Bangalore
31        1032  Customer_32      USA        Texas       Pune
32        1033  Customer_33    India       London     London

In [10]:
c[:5]

   CustomerID CustomerName  Country        State       City
0        1001   Customer_1  Germany   California     Austin
1        1002   Customer_2       UK   California  Bangalore
2        1003   Customer_3       UK  Maharashtra  Bangalore
3        1004   Customer_4      USA  Maharashtra     Mumbai
4        1005   Customer_5  Germany    Karnataka     Mumbai

In [11]:
c[5:]

    CustomerID CustomerName  Country        State       City
5         1006   Customer_6    India        Texas     London
6         1007   Customer_7      USA      Bavaria     Munich
7         1008   Customer_8  Germany        Texas     London
8         1009   Customer_9    India        Texas     Munich
9         1010  Customer_10       UK        Texas     Munich
10        1011  Customer_11       UK        Texas     Austin
11        1012  Customer_12       UK   California     Austin
12        1013  Customer_13      USA  Maharashtra     Munich
13        1014  Customer_14      USA    Karnataka     London
14        1015  Customer_15      USA    Karnataka     London
15        1016  Customer_16    India   California     Mumbai
16        1017  Customer_17      USA        Texas       Pune
17        1018  Customer_18       UK      Bavaria     Austin
18        1019  Customer_19    India   California  Bangalore
19        1020  Customer_20    India        Texas  Bangalore
20        1021  Customer_21  Germany    Karnataka     London
21        1022  Customer_22       UK      Bavaria     Austin
22        1023  Customer_23  Germany      Bavaria  Bangalore
23        1024  Customer_24       UK  Maharashtra     Mumbai
24        1025  Customer_25    India   California     Austin
25        1026  Customer_26  Germany      Bavaria     Austin
26        1027  Customer_27    India    Karnataka     Austin
27        1028  Customer_28       UK       London     Munich
28        1029  Customer_29  Germany   California     London
29        1030  Customer_30    India   California     Munich
30        1031  Customer_31       UK        Texas  Bangalore
31        1032  Customer_32      USA        Texas       Pune
32        1033  Customer_33    India       London     London
33        1034  Customer_34       UK      Bavaria     Munich
34        1035  Customer_35    India       London     Munich
35        1036  Customer_36    India    Karnataka       Pune
36        1037  Customer_37       UK        Texas     Austin
37        1038  Customer_38  Germany      Bavaria  Bangalore
38        1039  Customer_39  Germany   California       Pune
39        1040  Customer_40      USA   California       Pune
40        1041  Customer_41  Germany       London       Pune
41        1042  Customer_42  Germany    Karnataka     Munich
42        1043  Customer_43      USA        Texas     Mumbai
43        1044  Customer_44  Germany      Bavaria     Mumbai
44        1045  Customer_45    India    Karnataka     London
45        1046  Customer_46  Germany        Texas     Mumbai
46        1047  Customer_47      USA   California  Bangalore
47        1048  Customer_48  Germany  Maharashtra  Bangalore
48        1049  Customer_49  Germany   California     London
49        1050  Customer_50       UK   California     Austin

In [12]:
print(type(c))

<class 'pandas.DataFrame'>

In [13]:
c.index.array

<NumpyExtensionArray>
[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]
Length: 50, dtype: int64

In [14]:
c.to_numpy()

array([[1001, 'Customer_1', 'Germany', 'California', 'Austin'],
       [1002, 'Customer_2', 'UK', 'California', 'Bangalore'],
       [1003, 'Customer_3', 'UK', 'Maharashtra', 'Bangalore'],
       [1004, 'Customer_4', 'USA', 'Maharashtra', 'Mumbai'],
       [1005, 'Customer_5', 'Germany', 'Karnataka', 'Mumbai'],
       [1006, 'Customer_6', 'India', 'Texas', 'London'],
       [1007, 'Customer_7', 'USA', 'Bavaria', 'Munich'],
       [1008, 'Customer_8', 'Germany', 'Texas', 'London'],
       [1009, 'Customer_9', 'India', 'Texas', 'Munich'],
       [1010, 'Customer_10', 'UK', 'Texas', 'Munich'],
       [1011, 'Customer_11', 'UK', 'Texas', 'Austin'],
       [1012, 'Customer_12', 'UK', 'California', 'Austin'],
       [1013, 'Customer_13', 'USA', 'Maharashtra', 'Munich'],
       [1014, 'Customer_14', 'USA', 'Karnataka', 'London'],
       [1015, 'Customer_15', 'USA', 'Karnataka', 'London'],
       [1016, 'Customer_16', 'India', 'California', 'Mumbai'],
       [1017, 'Customer_17', 'USA', 'Texas', 'Pune'],
       [1018, 'Customer_18', 'UK', 'Bavaria', 'Austin'],
       [1019, 'Customer_19', 'India', 'California', 'Bangalore'],
       [1020, 'Customer_20', 'India', 'Texas', 'Bangalore'],
       [1021, 'Customer_21', 'Germany', 'Karnataka', 'London'],
       [1022, 'Customer_22', 'UK', 'Bavaria', 'Austin'],
       [1023, 'Customer_23', 'Germany', 'Bavaria', 'Bangalore'],
       [1024, 'Customer_24', 'UK', 'Maharashtra', 'Mumbai'],
       [1025, 'Customer_25', 'India', 'California', 'Austin'],
       [1026, 'Customer_26', 'Germany', 'Bavaria', 'Austin'],
       [1027, 'Customer_27', 'India', 'Karnataka', 'Austin'],
       [1028, 'Customer_28', 'UK', 'London', 'Munich'],
       [1029, 'Customer_29', 'Germany', 'California', 'London'],
       [1030, 'Customer_30', 'India', 'California', 'Munich'],
       [1031, 'Customer_31', 'UK', 'Texas', 'Bangalore'],
       [1032, 'Customer_32', 'USA', 'Texas', 'Pune'],
       [1033, 'Customer_33', 'India', 'London', 'London'],
       [1034, 'Customer_34', 'UK', 'Bavaria', 'Munich'],
       [1035, 'Customer_35', 'India', 'London', 'Munich'],
       [1036, 'Customer_36', 'India', 'Karnataka', 'Pune'],
       [1037, 'Customer_37', 'UK', 'Texas', 'Austin'],
       [1038, 'Customer_38', 'Germany', 'Bavaria', 'Bangalore'],
       [1039, 'Customer_39', 'Germany', 'California', 'Pune'],
       [1040, 'Customer_40', 'USA', 'California', 'Pune'],
       [1041, 'Customer_41', 'Germany', 'London', 'Pune'],
       [1042, 'Customer_42', 'Germany', 'Karnataka', 'Munich'],
       [1043, 'Customer_43', 'USA', 'Texas', 'Mumbai'],
       [1044, 'Customer_44', 'Germany', 'Bavaria', 'Mumbai'],
       [1045, 'Customer_45', 'India', 'Karnataka', 'London'],
       [1046, 'Customer_46', 'Germany', 'Texas', 'Mumbai'],
       [1047, 'Customer_47', 'USA', 'California', 'Bangalore'],
       [1048, 'Customer_48', 'Germany', 'Maharashtra', 'Bangalore'],
       [1049, 'Customer_49', 'Germany', 'California', 'London'],
       [1050, 'Customer_50', 'UK', 'California', 'Austin']], dtype=object)

In [15]:
import numpy as np
v = np.asarray(c)
v

array([[1001, 'Customer_1', 'Germany', 'California', 'Austin'],
       [1002, 'Customer_2', 'UK', 'California', 'Bangalore'],
       [1003, 'Customer_3', 'UK', 'Maharashtra', 'Bangalore'],
       [1004, 'Customer_4', 'USA', 'Maharashtra', 'Mumbai'],
       [1005, 'Customer_5', 'Germany', 'Karnataka', 'Mumbai'],
       [1006, 'Customer_6', 'India', 'Texas', 'London'],
       [1007, 'Customer_7', 'USA', 'Bavaria', 'Munich'],
       [1008, 'Customer_8', 'Germany', 'Texas', 'London'],
       [1009, 'Customer_9', 'India', 'Texas', 'Munich'],
       [1010, 'Customer_10', 'UK', 'Texas', 'Munich'],
       [1011, 'Customer_11', 'UK', 'Texas', 'Austin'],
       [1012, 'Customer_12', 'UK', 'California', 'Austin'],
       [1013, 'Customer_13', 'USA', 'Maharashtra', 'Munich'],
       [1014, 'Customer_14', 'USA', 'Karnataka', 'London'],
       [1015, 'Customer_15', 'USA', 'Karnataka', 'London'],
       [1016, 'Customer_16', 'India', 'California', 'Mumbai'],
       [1017, 'Customer_17', 'USA', 'Texas', 'Pune'],
       [1018, 'Customer_18', 'UK', 'Bavaria', 'Austin'],
       [1019, 'Customer_19', 'India', 'California', 'Bangalore'],
       [1020, 'Customer_20', 'India', 'Texas', 'Bangalore'],
       [1021, 'Customer_21', 'Germany', 'Karnataka', 'London'],
       [1022, 'Customer_22', 'UK', 'Bavaria', 'Austin'],
       [1023, 'Customer_23', 'Germany', 'Bavaria', 'Bangalore'],
       [1024, 'Customer_24', 'UK', 'Maharashtra', 'Mumbai'],
       [1025, 'Customer_25', 'India', 'California', 'Austin'],
       [1026, 'Customer_26', 'Germany', 'Bavaria', 'Austin'],
       [1027, 'Customer_27', 'India', 'Karnataka', 'Austin'],
       [1028, 'Customer_28', 'UK', 'London', 'Munich'],
       [1029, 'Customer_29', 'Germany', 'California', 'London'],
       [1030, 'Customer_30', 'India', 'California', 'Munich'],
       [1031, 'Customer_31', 'UK', 'Texas', 'Bangalore'],
       [1032, 'Customer_32', 'USA', 'Texas', 'Pune'],
       [1033, 'Customer_33', 'India', 'London', 'London'],
       [1034, 'Customer_34', 'UK', 'Bavaria', 'Munich'],
       [1035, 'Customer_35', 'India', 'London', 'Munich'],
       [1036, 'Customer_36', 'India', 'Karnataka', 'Pune'],
       [1037, 'Customer_37', 'UK', 'Texas', 'Austin'],
       [1038, 'Customer_38', 'Germany', 'Bavaria', 'Bangalore'],
       [1039, 'Customer_39', 'Germany', 'California', 'Pune'],
       [1040, 'Customer_40', 'USA', 'California', 'Pune'],
       [1041, 'Customer_41', 'Germany', 'London', 'Pune'],
       [1042, 'Customer_42', 'Germany', 'Karnataka', 'Munich'],
       [1043, 'Customer_43', 'USA', 'Texas', 'Mumbai'],
       [1044, 'Customer_44', 'Germany', 'Bavaria', 'Mumbai'],
       [1045, 'Customer_45', 'India', 'Karnataka', 'London'],
       [1046, 'Customer_46', 'Germany', 'Texas', 'Mumbai'],
       [1047, 'Customer_47', 'USA', 'California', 'Bangalore'],
       [1048, 'Customer_48', 'Germany', 'Maharashtra', 'Bangalore'],
       [1049, 'Customer_49', 'Germany', 'California', 'London'],
       [1050, 'Customer_50', 'UK', 'California', 'Austin']], dtype=object)

In [17]:
c.sort_index(axis=0,ascending=False)

    CustomerID CustomerName  Country        State       City
49        1050  Customer_50       UK   California     Austin
48        1049  Customer_49  Germany   California     London
47        1048  Customer_48  Germany  Maharashtra  Bangalore
46        1047  Customer_47      USA   California  Bangalore
45        1046  Customer_46  Germany        Texas     Mumbai
44        1045  Customer_45    India    Karnataka     London
43        1044  Customer_44  Germany      Bavaria     Mumbai
42        1043  Customer_43      USA        Texas     Mumbai
41        1042  Customer_42  Germany    Karnataka     Munich
40        1041  Customer_41  Germany       London       Pune
39        1040  Customer_40      USA   California       Pune
38        1039  Customer_39  Germany   California       Pune
37        1038  Customer_38  Germany      Bavaria  Bangalore
36        1037  Customer_37       UK        Texas     Austin
35        1036  Customer_36    India    Karnataka       Pune
34        1035  Customer_35    India       London     Munich
33        1034  Customer_34       UK      Bavaria     Munich
32        1033  Customer_33    India       London     London
31        1032  Customer_32      USA        Texas       Pune
30        1031  Customer_31       UK        Texas  Bangalore
29        1030  Customer_30    India   California     Munich
28        1029  Customer_29  Germany   California     London
27        1028  Customer_28       UK       London     Munich
26        1027  Customer_27    India    Karnataka     Austin
25        1026  Customer_26  Germany      Bavaria     Austin
24        1025  Customer_25    India   California     Austin
23        1024  Customer_24       UK  Maharashtra     Mumbai
22        1023  Customer_23  Germany      Bavaria  Bangalore
21        1022  Customer_22       UK      Bavaria     Austin
20        1021  Customer_21  Germany    Karnataka     London
19        1020  Customer_20    India        Texas  Bangalore
18        1019  Customer_19    India   California  Bangalore
17        1018  Customer_18       UK      Bavaria     Austin
16        1017  Customer_17      USA        Texas       Pune
15        1016  Customer_16    India   California     Mumbai
14        1015  Customer_15      USA    Karnataka     London
13        1014  Customer_14      USA    Karnataka     London
12        1013  Customer_13      USA  Maharashtra     Munich
11        1012  Customer_12       UK   California     Austin
10        1011  Customer_11       UK        Texas     Austin
9         1010  Customer_10       UK        Texas     Munich
8         1009   Customer_9    India        Texas     Munich
7         1008   Customer_8  Germany        Texas     London
6         1007   Customer_7      USA      Bavaria     Munich
5         1006   Customer_6    India        Texas     London
4         1005   Customer_5  Germany    Karnataka     Mumbai
3         1004   Customer_4      USA  Maharashtra     Mumbai
2         1003   Customer_3       UK  Maharashtra  Bangalore
1         1002   Customer_2       UK   California  Bangalore
0         1001   Customer_1  Germany   California     Austin

In [19]:
c["CustomerName"][0]="python"
c

C:\Users\yadav\AppData\Local\Temp\ipykernel_7028\144581540.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  c["CustomerName"][0]="python"

    CustomerID CustomerName  Country        State       City
0         1001   Customer_1  Germany   California     Austin
1         1002   Customer_2       UK   California  Bangalore
2         1003   Customer_3       UK  Maharashtra  Bangalore
3         1004   Customer_4      USA  Maharashtra     Mumbai
4         1005   Customer_5  Germany    Karnataka     Mumbai
5         1006   Customer_6    India        Texas     London
6         1007   Customer_7      USA      Bavaria     Munich
7         1008   Customer_8  Germany        Texas     London
8         1009   Customer_9    India        Texas     Munich
9         1010  Customer_10       UK        Texas     Munich
10        1011  Customer_11       UK        Texas     Austin
11        1012  Customer_12       UK   California     Austin
12        1013  Customer_13      USA  Maharashtra     Munich
13        1014  Customer_14      USA    Karnataka     London
14        1015  Customer_15      USA    Karnataka     London
15        1016  Customer_16    India   California     Mumbai
16        1017  Customer_17      USA        Texas       Pune
17        1018  Customer_18       UK      Bavaria     Austin
18        1019  Customer_19    India   California  Bangalore
19        1020  Customer_20    India        Texas  Bangalore
20        1021  Customer_21  Germany    Karnataka     London
21        1022  Customer_22       UK      Bavaria     Austin
22        1023  Customer_23  Germany      Bavaria  Bangalore
23        1024  Customer_24       UK  Maharashtra     Mumbai
24        1025  Customer_25    India   California     Austin
25        1026  Customer_26  Germany      Bavaria     Austin
26        1027  Customer_27    India    Karnataka     Austin
27        1028  Customer_28       UK       London     Munich
28        1029  Customer_29  Germany   California     London
29        1030  Customer_30    India   California     Munich
30        1031  Customer_31       UK        Texas  Bangalore
31        1032  Customer_32      USA        Texas       Pune
32        1033  Customer_33    India       London     London
33        1034  Customer_34       UK      Bavaria     Munich
34        1035  Customer_35    India       London     Munich
35        1036  Customer_36    India    Karnataka       Pune
36        1037  Customer_37       UK        Texas     Austin
37        1038  Customer_38  Germany      Bavaria  Bangalore
38        1039  Customer_39  Germany   California       Pune
39        1040  Customer_40      USA   California       Pune
40        1041  Customer_41  Germany       London       Pune
41        1042  Customer_42  Germany    Karnataka     Munich
42        1043  Customer_43      USA        Texas     Mumbai
43        1044  Customer_44  Germany      Bavaria     Mumbai
44        1045  Customer_45    India    Karnataka     London
45        1046  Customer_46  Germany        Texas     Mumbai
46        1047  Customer_47      USA   California  Bangalore
47        1048  Customer_48  Germany  Maharashtra  Bangalore
48        1049  Customer_49  Germany   California     London
49        1050  Customer_50       UK   California     Austin

In [20]:
c.loc[1,"CustomerName"]="Nitu"
c

    CustomerID CustomerName  Country        State       City
0         1001   Customer_1  Germany   California     Austin
1         1002         Nitu       UK   California  Bangalore
2         1003   Customer_3       UK  Maharashtra  Bangalore
3         1004   Customer_4      USA  Maharashtra     Mumbai
4         1005   Customer_5  Germany    Karnataka     Mumbai
5         1006   Customer_6    India        Texas     London
6         1007   Customer_7      USA      Bavaria     Munich
7         1008   Customer_8  Germany        Texas     London
8         1009   Customer_9    India        Texas     Munich
9         1010  Customer_10       UK        Texas     Munich
10        1011  Customer_11       UK        Texas     Austin
11        1012  Customer_12       UK   California     Austin
12        1013  Customer_13      USA  Maharashtra     Munich
13        1014  Customer_14      USA    Karnataka     London
14        1015  Customer_15      USA    Karnataka     London
15        1016  Customer_16    India   California     Mumbai
16        1017  Customer_17      USA        Texas       Pune
17        1018  Customer_18       UK      Bavaria     Austin
18        1019  Customer_19    India   California  Bangalore
19        1020  Customer_20    India        Texas  Bangalore
20        1021  Customer_21  Germany    Karnataka     London
21        1022  Customer_22       UK      Bavaria     Austin
22        1023  Customer_23  Germany      Bavaria  Bangalore
23        1024  Customer_24       UK  Maharashtra     Mumbai
24        1025  Customer_25    India   California     Austin
25        1026  Customer_26  Germany      Bavaria     Austin
26        1027  Customer_27    India    Karnataka     Austin
27        1028  Customer_28       UK       London     Munich
28        1029  Customer_29  Germany   California     London
29        1030  Customer_30    India   California     Munich
30        1031  Customer_31       UK        Texas  Bangalore
31        1032  Customer_32      USA        Texas       Pune
32        1033  Customer_33    India       London     London
33        1034  Customer_34       UK      Bavaria     Munich
34        1035  Customer_35    India       London     Munich
35        1036  Customer_36    India    Karnataka       Pune
36        1037  Customer_37       UK        Texas     Austin
37        1038  Customer_38  Germany      Bavaria  Bangalore
38        1039  Customer_39  Germany   California       Pune
39        1040  Customer_40      USA   California       Pune
40        1041  Customer_41  Germany       London       Pune
41        1042  Customer_42  Germany    Karnataka     Munich
42        1043  Customer_43      USA        Texas     Mumbai
43        1044  Customer_44  Germany      Bavaria     Mumbai
44        1045  Customer_45    India    Karnataka     London
45        1046  Customer_46  Germany        Texas     Mumbai
46        1047  Customer_47      USA   California  Bangalore
47        1048  Customer_48  Germany  Maharashtra  Bangalore
48        1049  Customer_49  Germany   California     London
49        1050  Customer_50       UK   California     Austin

In [22]:
c.loc[[2,3],["CustomerName"]]

  CustomerName
2   Customer_3
3   Customer_4

In [23]:
c.loc[:,["CustomerName"]]

   CustomerName
0    Customer_1
1          Nitu
2    Customer_3
3    Customer_4
4    Customer_5
5    Customer_6
6    Customer_7
7    Customer_8
8    Customer_9
9   Customer_10
10  Customer_11
11  Customer_12
12  Customer_13
13  Customer_14
14  Customer_15
15  Customer_16
16  Customer_17
17  Customer_18
18  Customer_19
19  Customer_20
20  Customer_21
21  Customer_22
22  Customer_23
23  Customer_24
24  Customer_25
25  Customer_26
26  Customer_27
27  Customer_28
28  Customer_29
29  Customer_30
30  Customer_31
31  Customer_32
32  Customer_33
33  Customer_34
34  Customer_35
35  Customer_36
36  Customer_37
37  Customer_38
38  Customer_39
39  Customer_40
40  Customer_41
41  Customer_42
42  Customer_43
43  Customer_44
44  Customer_45
45  Customer_46
46  Customer_47
47  Customer_48
48  Customer_49
49  Customer_50

In [24]:
c.iloc[2,3]

'Maharashtra'

In [25]:
c.iloc[1,1]

'Nitu'

In [28]:
c.drop("CustomerName",axis=1)

    CustomerID  Country        State       City
0         1001  Germany   California     Austin
1         1002       UK   California  Bangalore
2         1003       UK  Maharashtra  Bangalore
3         1004      USA  Maharashtra     Mumbai
4         1005  Germany    Karnataka     Mumbai
5         1006    India        Texas     London
6         1007      USA      Bavaria     Munich
7         1008  Germany        Texas     London
8         1009    India        Texas     Munich
9         1010       UK        Texas     Munich
10        1011       UK        Texas     Austin
11        1012       UK   California     Austin
12        1013      USA  Maharashtra     Munich
13        1014      USA    Karnataka     London
14        1015      USA    Karnataka     London
15        1016    India   California     Mumbai
16        1017      USA        Texas       Pune
17        1018       UK      Bavaria     Austin
18        1019    India   California  Bangalore
19        1020    India        Texas  Bangalore
20        1021  Germany    Karnataka     London
21        1022       UK      Bavaria     Austin
22        1023  Germany      Bavaria  Bangalore
23        1024       UK  Maharashtra     Mumbai
24        1025    India   California     Austin
25        1026  Germany      Bavaria     Austin
26        1027    India    Karnataka     Austin
27        1028       UK       London     Munich
28        1029  Germany   California     London
29        1030    India   California     Munich
30        1031       UK        Texas  Bangalore
31        1032      USA        Texas       Pune
32        1033    India       London     London
33        1034       UK      Bavaria     Munich
34        1035    India       London     Munich
35        1036    India    Karnataka       Pune
36        1037       UK        Texas     Austin
37        1038  Germany      Bavaria  Bangalore
38        1039  Germany   California       Pune
39        1040      USA   California       Pune
40        1041  Germany       London       Pune
41        1042  Germany    Karnataka     Munich
42        1043      USA        Texas     Mumbai
43        1044  Germany      Bavaria     Mumbai
44        1045    India    Karnataka     London
45        1046  Germany        Texas     Mumbai
46        1047      USA   California  Bangalore
47        1048  Germany  Maharashtra  Bangalore
48        1049  Germany   California     London
49        1050       UK   California     Austin