In [ ]:
#Group By

In [2]:
import pandas as pd

var = pd.DataFrame({"name":["a","a","b",'f','f','c','b','b','d',],
                     "sub1":[12,13,12,13,14,15,16,14,54],
                     "sub2":[21,32,43,23,34,54,45,65,56]
                    })
var

  name  sub1  sub2
0    a    12    21
1    a    13    32
2    b    12    43
3    f    13    23
4    f    14    34
5    c    15    54
6    b    16    45
7    b    14    65
8    d    54    56

In [3]:
new_var = var.groupby("name")
new_var

In [4]:
for x,y in new_var:
    print(x)
    print(y)

a
  name  sub1  sub2
0    a    12    21
1    a    13    32
b
  name  sub1  sub2
2    b    12    43
6    b    16    45
7    b    14    65
c
  name  sub1  sub2
5    c    15    54
d
  name  sub1  sub2
8    d    54    56
f
  name  sub1  sub2
3    f    13    23
4    f    14    34

In [5]:
new_var.get_group("a")

  name  sub1  sub2
0    a    12    21
1    a    13    32

In [6]:
new_var.get_group("f")

  name  sub1  sub2
3    f    13    23
4    f    14    34

In [8]:
new_var.min()

      sub1  sub2
name
a       12    21
b       12    43
c       15    54
d       54    56
f       13    23

In [9]:
new_var.max()

      sub1  sub2
name
a       13    32
b       16    65
c       15    54
d       54    56
f       14    34

In [10]:
new_var.sum()

      sub1  sub2
name
a       25    53
b       42   153
c       15    54
d       54    56
f       27    57

In [11]:
new_var.count()

      sub1  sub2
name
a        2     2
b        3     3
c        1     1
d        1     1
f        2     2