In [ ]:
#Handling Missing Data (Dropna & Fillna)

In [11]:
import pandas as pd

cs = pd.read_csv(r"C:\Users\yadav\OneDrive\Desktop\Documents\Book1.csv")

cs

,EmpID,EmpName,Email,Phone,Department
0,1001,Rohit Yadav,rohit.yadav1@example.com,9.111268e+09,Sales
1,1002,Meer Mehta,meera.mehta2@example.com,9.150787e+09,Operations
2,1003,NaN,kavya.rao3@example.com,9.310475e+09,Sales
3,1005,Sachin Joshi,sachin.joshi5@example.com,9.152289e+09,Operations
4,1006,Vikas Joshi,vikas.joshi6@example.com,9.775118e+08,Marketing
5,1008,Rahul Rao,rahul.rao8@example.com,9.918615e+09,Sales
6,1009,Nitin Iyer,nitin.iyer9@example.com,9.407051e+09,Marketing
7,1010,Sachin Shah,sachin.shah10@example.com,9.553605e+09,HR
8,1013,Neha Reddy,neha.reddy13@example.com,9.240042e+09,IT
9,1015,NaN,manoj.kapoor15@example.com,NaN,HR
10,1016,Amit Sharma,amit.sharma16@example.com,9.688355e+09,HR
11,1018,Deepak Shah,deepak.shah18@example.com,9.731236e+09,Sales
12,1020,Nitin Khan,nitin.khan20@example.com,9.899424e+09,HR
13,1021,NaN,karan.yadav21@example.com,9.737537e+09,Marketing
14,1022,Sachin Das,sachin.das22@example.com,9.666161e+09,IT
15,1023,Amit Yadav,amit.yadav23@example.com,9.980491e+09,Operations
16,1024,Arjun Mishra,arjun.mishra24@example.com,9.203299e+09,HR
17,1025,Meera Das,meera.das25@example.com,NaN,IT
18,1029,Priya Kulkarni,priya.kulkarni29@example.com,9.631158e+09,NaN
19,1030,Rohit Mishra,rohit.mishra30@example.com,9.130307e+09,Marketing
20,1031,NaN,arjun.yadav31@example.com,9.998462e+09,Marketing
21,1032,Nitin Mehta,nitin.mehta32@example.com,9.803409e+09,NaN
22,1033,Ritika Rao,ritika.rao33@example.com,9.172254e+09,HR
23,1034,Nitin Gupta,nitin.gupta34@example.com,9.200346e+09,IT
24,1035,NaN,NaN,NaN,NaN
25,1036,NaN,NaN,NaN,NaN

In [12]:
cs.dropna()

    EmpID       EmpName                       Email         Phone  Department
0    1001   Rohit Yadav    rohit.yadav1@example.com  9.111268e+09       Sales
1    1002    Meer Mehta    meera.mehta2@example.com  9.150787e+09  Operations
3    1005  Sachin Joshi   sachin.joshi5@example.com  9.152289e+09  Operations
4    1006   Vikas Joshi    vikas.joshi6@example.com  9.775118e+08   Marketing
5    1008     Rahul Rao      rahul.rao8@example.com  9.918615e+09       Sales
6    1009    Nitin Iyer     nitin.iyer9@example.com  9.407051e+09   Marketing
7    1010   Sachin Shah   sachin.shah10@example.com  9.553605e+09          HR
8    1013    Neha Reddy    neha.reddy13@example.com  9.240042e+09          IT
10   1016   Amit Sharma   amit.sharma16@example.com  9.688355e+09          HR
11   1018   Deepak Shah   deepak.shah18@example.com  9.731236e+09       Sales
12   1020    Nitin Khan    nitin.khan20@example.com  9.899424e+09          HR
14   1022    Sachin Das    sachin.das22@example.com  9.666161e+09          IT
15   1023    Amit Yadav    amit.yadav23@example.com  9.980491e+09  Operations
16   1024  Arjun Mishra  arjun.mishra24@example.com  9.203299e+09          HR
19   1030  Rohit Mishra  rohit.mishra30@example.com  9.130307e+09   Marketing
22   1033    Ritika Rao    ritika.rao33@example.com  9.172254e+09          HR
23   1034   Nitin Gupta   nitin.gupta34@example.com  9.200346e+09          IT

In [13]:
cs.dropna(axis=1)

    EmpID
0    1001
1    1002
2    1003
3    1005
4    1006
5    1008
6    1009
7    1010
8    1013
9    1015
10   1016
11   1018
12   1020
13   1021
14   1022
15   1023
16   1024
17   1025
18   1029
19   1030
20   1031
21   1032
22   1033
23   1034
24   1035
25   1036

In [14]:
cs.dropna(axis=0)

    EmpID       EmpName                       Email         Phone  Department
0    1001   Rohit Yadav    rohit.yadav1@example.com  9.111268e+09       Sales
1    1002    Meer Mehta    meera.mehta2@example.com  9.150787e+09  Operations
3    1005  Sachin Joshi   sachin.joshi5@example.com  9.152289e+09  Operations
4    1006   Vikas Joshi    vikas.joshi6@example.com  9.775118e+08   Marketing
5    1008     Rahul Rao      rahul.rao8@example.com  9.918615e+09       Sales
6    1009    Nitin Iyer     nitin.iyer9@example.com  9.407051e+09   Marketing
7    1010   Sachin Shah   sachin.shah10@example.com  9.553605e+09          HR
8    1013    Neha Reddy    neha.reddy13@example.com  9.240042e+09          IT
10   1016   Amit Sharma   amit.sharma16@example.com  9.688355e+09          HR
11   1018   Deepak Shah   deepak.shah18@example.com  9.731236e+09       Sales
12   1020    Nitin Khan    nitin.khan20@example.com  9.899424e+09          HR
14   1022    Sachin Das    sachin.das22@example.com  9.666161e+09          IT
15   1023    Amit Yadav    amit.yadav23@example.com  9.980491e+09  Operations
16   1024  Arjun Mishra  arjun.mishra24@example.com  9.203299e+09          HR
19   1030  Rohit Mishra  rohit.mishra30@example.com  9.130307e+09   Marketing
22   1033    Ritika Rao    ritika.rao33@example.com  9.172254e+09          HR
23   1034   Nitin Gupta   nitin.gupta34@example.com  9.200346e+09          IT

In [18]:
cs.dropna(how="any")

    EmpID       EmpName                       Email         Phone  Department
0    1001   Rohit Yadav    rohit.yadav1@example.com  9.111268e+09       Sales
1    1002    Meer Mehta    meera.mehta2@example.com  9.150787e+09  Operations
3    1005  Sachin Joshi   sachin.joshi5@example.com  9.152289e+09  Operations
4    1006   Vikas Joshi    vikas.joshi6@example.com  9.775118e+08   Marketing
5    1008     Rahul Rao      rahul.rao8@example.com  9.918615e+09       Sales
6    1009    Nitin Iyer     nitin.iyer9@example.com  9.407051e+09   Marketing
7    1010   Sachin Shah   sachin.shah10@example.com  9.553605e+09          HR
8    1013    Neha Reddy    neha.reddy13@example.com  9.240042e+09          IT
10   1016   Amit Sharma   amit.sharma16@example.com  9.688355e+09          HR
11   1018   Deepak Shah   deepak.shah18@example.com  9.731236e+09       Sales
12   1020    Nitin Khan    nitin.khan20@example.com  9.899424e+09          HR
14   1022    Sachin Das    sachin.das22@example.com  9.666161e+09          IT
15   1023    Amit Yadav    amit.yadav23@example.com  9.980491e+09  Operations
16   1024  Arjun Mishra  arjun.mishra24@example.com  9.203299e+09          HR
19   1030  Rohit Mishra  rohit.mishra30@example.com  9.130307e+09   Marketing
22   1033    Ritika Rao    ritika.rao33@example.com  9.172254e+09          HR
23   1034   Nitin Gupta   nitin.gupta34@example.com  9.200346e+09          IT

In [17]:
cs.dropna(how="all")

,EmpID,EmpName,Email,Phone,Department
0,1001,Rohit Yadav,rohit.yadav1@example.com,9.111268e+09,Sales
1,1002,Meer Mehta,meera.mehta2@example.com,9.150787e+09,Operations
2,1003,NaN,kavya.rao3@example.com,9.310475e+09,Sales
3,1005,Sachin Joshi,sachin.joshi5@example.com,9.152289e+09,Operations
4,1006,Vikas Joshi,vikas.joshi6@example.com,9.775118e+08,Marketing
5,1008,Rahul Rao,rahul.rao8@example.com,9.918615e+09,Sales
6,1009,Nitin Iyer,nitin.iyer9@example.com,9.407051e+09,Marketing
7,1010,Sachin Shah,sachin.shah10@example.com,9.553605e+09,HR
8,1013,Neha Reddy,neha.reddy13@example.com,9.240042e+09,IT
9,1015,NaN,manoj.kapoor15@example.com,NaN,HR
10,1016,Amit Sharma,amit.sharma16@example.com,9.688355e+09,HR
11,1018,Deepak Shah,deepak.shah18@example.com,9.731236e+09,Sales
12,1020,Nitin Khan,nitin.khan20@example.com,9.899424e+09,HR
13,1021,NaN,karan.yadav21@example.com,9.737537e+09,Marketing
14,1022,Sachin Das,sachin.das22@example.com,9.666161e+09,IT
15,1023,Amit Yadav,amit.yadav23@example.com,9.980491e+09,Operations
16,1024,Arjun Mishra,arjun.mishra24@example.com,9.203299e+09,HR
17,1025,Meera Das,meera.das25@example.com,NaN,IT
18,1029,Priya Kulkarni,priya.kulkarni29@example.com,9.631158e+09,NaN
19,1030,Rohit Mishra,rohit.mishra30@example.com,9.130307e+09,Marketing
20,1031,NaN,arjun.yadav31@example.com,9.998462e+09,Marketing
21,1032,Nitin Mehta,nitin.mehta32@example.com,9.803409e+09,NaN
22,1033,Ritika Rao,ritika.rao33@example.com,9.172254e+09,HR
23,1034,Nitin Gupta,nitin.gupta34@example.com,9.200346e+09,IT
24,1035,NaN,NaN,NaN,NaN
25,1036,NaN,NaN,NaN,NaN

In [19]:
cs.dropna(subset="EmpName")

,EmpID,EmpName,Email,Phone,Department
0,1001,Rohit Yadav,rohit.yadav1@example.com,9.111268e+09,Sales
1,1002,Meer Mehta,meera.mehta2@example.com,9.150787e+09,Operations
3,1005,Sachin Joshi,sachin.joshi5@example.com,9.152289e+09,Operations
4,1006,Vikas Joshi,vikas.joshi6@example.com,9.775118e+08,Marketing
5,1008,Rahul Rao,rahul.rao8@example.com,9.918615e+09,Sales
6,1009,Nitin Iyer,nitin.iyer9@example.com,9.407051e+09,Marketing
7,1010,Sachin Shah,sachin.shah10@example.com,9.553605e+09,HR
8,1013,Neha Reddy,neha.reddy13@example.com,9.240042e+09,IT
10,1016,Amit Sharma,amit.sharma16@example.com,9.688355e+09,HR
11,1018,Deepak Shah,deepak.shah18@example.com,9.731236e+09,Sales
12,1020,Nitin Khan,nitin.khan20@example.com,9.899424e+09,HR
14,1022,Sachin Das,sachin.das22@example.com,9.666161e+09,IT
15,1023,Amit Yadav,amit.yadav23@example.com,9.980491e+09,Operations
16,1024,Arjun Mishra,arjun.mishra24@example.com,9.203299e+09,HR
17,1025,Meera Das,meera.das25@example.com,NaN,IT
18,1029,Priya Kulkarni,priya.kulkarni29@example.com,9.631158e+09,NaN
19,1030,Rohit Mishra,rohit.mishra30@example.com,9.130307e+09,Marketing
21,1032,Nitin Mehta,nitin.mehta32@example.com,9.803409e+09,NaN
22,1033,Ritika Rao,ritika.rao33@example.com,9.172254e+09,HR
23,1034,Nitin Gupta,nitin.gupta34@example.com,9.200346e+09,IT

In [21]:
cs.dropna(subset=["Phone"])

,EmpID,EmpName,Email,Phone,Department
0,1001,Rohit Yadav,rohit.yadav1@example.com,9.111268e+09,Sales
1,1002,Meer Mehta,meera.mehta2@example.com,9.150787e+09,Operations
2,1003,NaN,kavya.rao3@example.com,9.310475e+09,Sales
3,1005,Sachin Joshi,sachin.joshi5@example.com,9.152289e+09,Operations
4,1006,Vikas Joshi,vikas.joshi6@example.com,9.775118e+08,Marketing
5,1008,Rahul Rao,rahul.rao8@example.com,9.918615e+09,Sales
6,1009,Nitin Iyer,nitin.iyer9@example.com,9.407051e+09,Marketing
7,1010,Sachin Shah,sachin.shah10@example.com,9.553605e+09,HR
8,1013,Neha Reddy,neha.reddy13@example.com,9.240042e+09,IT
10,1016,Amit Sharma,amit.sharma16@example.com,9.688355e+09,HR
11,1018,Deepak Shah,deepak.shah18@example.com,9.731236e+09,Sales
12,1020,Nitin Khan,nitin.khan20@example.com,9.899424e+09,HR
13,1021,NaN,karan.yadav21@example.com,9.737537e+09,Marketing
14,1022,Sachin Das,sachin.das22@example.com,9.666161e+09,IT
15,1023,Amit Yadav,amit.yadav23@example.com,9.980491e+09,Operations
16,1024,Arjun Mishra,arjun.mishra24@example.com,9.203299e+09,HR
18,1029,Priya Kulkarni,priya.kulkarni29@example.com,9.631158e+09,NaN
19,1030,Rohit Mishra,rohit.mishra30@example.com,9.130307e+09,Marketing
20,1031,NaN,arjun.yadav31@example.com,9.998462e+09,Marketing
21,1032,Nitin Mehta,nitin.mehta32@example.com,9.803409e+09,NaN
22,1033,Ritika Rao,ritika.rao33@example.com,9.172254e+09,HR
23,1034,Nitin Gupta,nitin.gupta34@example.com,9.200346e+09,IT

In [23]:
cs.dropna(thresh=2)

,EmpID,EmpName,Email,Phone,Department
0,1001,Rohit Yadav,rohit.yadav1@example.com,9.111268e+09,Sales
1,1002,Meer Mehta,meera.mehta2@example.com,9.150787e+09,Operations
2,1003,NaN,kavya.rao3@example.com,9.310475e+09,Sales
3,1005,Sachin Joshi,sachin.joshi5@example.com,9.152289e+09,Operations
4,1006,Vikas Joshi,vikas.joshi6@example.com,9.775118e+08,Marketing
5,1008,Rahul Rao,rahul.rao8@example.com,9.918615e+09,Sales
6,1009,Nitin Iyer,nitin.iyer9@example.com,9.407051e+09,Marketing
7,1010,Sachin Shah,sachin.shah10@example.com,9.553605e+09,HR
8,1013,Neha Reddy,neha.reddy13@example.com,9.240042e+09,IT
9,1015,NaN,manoj.kapoor15@example.com,NaN,HR
10,1016,Amit Sharma,amit.sharma16@example.com,9.688355e+09,HR
11,1018,Deepak Shah,deepak.shah18@example.com,9.731236e+09,Sales
12,1020,Nitin Khan,nitin.khan20@example.com,9.899424e+09,HR
13,1021,NaN,karan.yadav21@example.com,9.737537e+09,Marketing
14,1022,Sachin Das,sachin.das22@example.com,9.666161e+09,IT
15,1023,Amit Yadav,amit.yadav23@example.com,9.980491e+09,Operations
16,1024,Arjun Mishra,arjun.mishra24@example.com,9.203299e+09,HR
17,1025,Meera Das,meera.das25@example.com,NaN,IT
18,1029,Priya Kulkarni,priya.kulkarni29@example.com,9.631158e+09,NaN
19,1030,Rohit Mishra,rohit.mishra30@example.com,9.130307e+09,Marketing
20,1031,NaN,arjun.yadav31@example.com,9.998462e+09,Marketing
21,1032,Nitin Mehta,nitin.mehta32@example.com,9.803409e+09,NaN
22,1033,Ritika Rao,ritika.rao33@example.com,9.172254e+09,HR
23,1034,Nitin Gupta,nitin.gupta34@example.com,9.200346e+09,IT

In [ ]:
#Fillna

In [24]:
cs.fillna("NITU")

,EmpID,EmpName,Email,Phone,Department
0,1001,Rohit Yadav,rohit.yadav1@example.com,9111268039.0,Sales
1,1002,Meer Mehta,meera.mehta2@example.com,9150786963.0,Operations
2,1003,NITU,kavya.rao3@example.com,9310474687.0,Sales
3,1005,Sachin Joshi,sachin.joshi5@example.com,9152289378.0,Operations
4,1006,Vikas Joshi,vikas.joshi6@example.com,977511850.0,Marketing
5,1008,Rahul Rao,rahul.rao8@example.com,9918615372.0,Sales
6,1009,Nitin Iyer,nitin.iyer9@example.com,9407050929.0,Marketing
7,1010,Sachin Shah,sachin.shah10@example.com,9553605379.0,HR
8,1013,Neha Reddy,neha.reddy13@example.com,9240042131.0,IT
9,1015,NITU,manoj.kapoor15@example.com,NITU,HR
10,1016,Amit Sharma,amit.sharma16@example.com,9688355238.0,HR
11,1018,Deepak Shah,deepak.shah18@example.com,9731235606.0,Sales
12,1020,Nitin Khan,nitin.khan20@example.com,9899423617.0,HR
13,1021,NITU,karan.yadav21@example.com,9737537455.0,Marketing
14,1022,Sachin Das,sachin.das22@example.com,9666160764.0,IT
15,1023,Amit Yadav,amit.yadav23@example.com,9980490847.0,Operations
16,1024,Arjun Mishra,arjun.mishra24@example.com,9203299493.0,HR
17,1025,Meera Das,meera.das25@example.com,NITU,IT
18,1029,Priya Kulkarni,priya.kulkarni29@example.com,9631158426.0,NITU
19,1030,Rohit Mishra,rohit.mishra30@example.com,9130306846.0,Marketing
20,1031,NITU,arjun.yadav31@example.com,9998462204.0,Marketing
21,1032,Nitin Mehta,nitin.mehta32@example.com,9803408828.0,NITU
22,1033,Ritika Rao,ritika.rao33@example.com,9172253721.0,HR
23,1034,Nitin Gupta,nitin.gupta34@example.com,9200345531.0,IT
24,1035,NITU,NITU,NITU,NITU
25,1036,NITU,NITU,NITU,NITU

In [25]:
cs.fillna({"Phone":"YADAV"})

,EmpID,EmpName,Email,Phone,Department
0,1001,Rohit Yadav,rohit.yadav1@example.com,9111268039.0,Sales
1,1002,Meer Mehta,meera.mehta2@example.com,9150786963.0,Operations
2,1003,NaN,kavya.rao3@example.com,9310474687.0,Sales
3,1005,Sachin Joshi,sachin.joshi5@example.com,9152289378.0,Operations
4,1006,Vikas Joshi,vikas.joshi6@example.com,977511850.0,Marketing
5,1008,Rahul Rao,rahul.rao8@example.com,9918615372.0,Sales
6,1009,Nitin Iyer,nitin.iyer9@example.com,9407050929.0,Marketing
7,1010,Sachin Shah,sachin.shah10@example.com,9553605379.0,HR
8,1013,Neha Reddy,neha.reddy13@example.com,9240042131.0,IT
9,1015,NaN,manoj.kapoor15@example.com,YADAV,HR
10,1016,Amit Sharma,amit.sharma16@example.com,9688355238.0,HR
11,1018,Deepak Shah,deepak.shah18@example.com,9731235606.0,Sales
12,1020,Nitin Khan,nitin.khan20@example.com,9899423617.0,HR
13,1021,NaN,karan.yadav21@example.com,9737537455.0,Marketing
14,1022,Sachin Das,sachin.das22@example.com,9666160764.0,IT
15,1023,Amit Yadav,amit.yadav23@example.com,9980490847.0,Operations
16,1024,Arjun Mishra,arjun.mishra24@example.com,9203299493.0,HR
17,1025,Meera Das,meera.das25@example.com,YADAV,IT
18,1029,Priya Kulkarni,priya.kulkarni29@example.com,9631158426.0,NaN
19,1030,Rohit Mishra,rohit.mishra30@example.com,9130306846.0,Marketing
20,1031,NaN,arjun.yadav31@example.com,9998462204.0,Marketing
21,1032,Nitin Mehta,nitin.mehta32@example.com,9803408828.0,NaN
22,1033,Ritika Rao,ritika.rao33@example.com,9172253721.0,HR
23,1034,Nitin Gupta,nitin.gupta34@example.com,9200345531.0,IT
24,1035,NaN,NaN,YADAV,NaN
25,1036,NaN,NaN,YADAV,NaN

In [26]:
cs.bfill()

,EmpID,EmpName,Email,Phone,Department
0,1001,Rohit Yadav,rohit.yadav1@example.com,9.111268e+09,Sales
1,1002,Meer Mehta,meera.mehta2@example.com,9.150787e+09,Operations
2,1003,Sachin Joshi,kavya.rao3@example.com,9.310475e+09,Sales
3,1005,Sachin Joshi,sachin.joshi5@example.com,9.152289e+09,Operations
4,1006,Vikas Joshi,vikas.joshi6@example.com,9.775118e+08,Marketing
5,1008,Rahul Rao,rahul.rao8@example.com,9.918615e+09,Sales
6,1009,Nitin Iyer,nitin.iyer9@example.com,9.407051e+09,Marketing
7,1010,Sachin Shah,sachin.shah10@example.com,9.553605e+09,HR
8,1013,Neha Reddy,neha.reddy13@example.com,9.240042e+09,IT
9,1015,Amit Sharma,manoj.kapoor15@example.com,9.688355e+09,HR
10,1016,Amit Sharma,amit.sharma16@example.com,9.688355e+09,HR
11,1018,Deepak Shah,deepak.shah18@example.com,9.731236e+09,Sales
12,1020,Nitin Khan,nitin.khan20@example.com,9.899424e+09,HR
13,1021,Sachin Das,karan.yadav21@example.com,9.737537e+09,Marketing
14,1022,Sachin Das,sachin.das22@example.com,9.666161e+09,IT
15,1023,Amit Yadav,amit.yadav23@example.com,9.980491e+09,Operations
16,1024,Arjun Mishra,arjun.mishra24@example.com,9.203299e+09,HR
17,1025,Meera Das,meera.das25@example.com,9.631158e+09,IT
18,1029,Priya Kulkarni,priya.kulkarni29@example.com,9.631158e+09,Marketing
19,1030,Rohit Mishra,rohit.mishra30@example.com,9.130307e+09,Marketing
20,1031,Nitin Mehta,arjun.yadav31@example.com,9.998462e+09,Marketing
21,1032,Nitin Mehta,nitin.mehta32@example.com,9.803409e+09,HR
22,1033,Ritika Rao,ritika.rao33@example.com,9.172254e+09,HR
23,1034,Nitin Gupta,nitin.gupta34@example.com,9.200346e+09,IT
24,1035,NaN,NaN,NaN,NaN
25,1036,NaN,NaN,NaN,NaN

In [28]:
cs.ffill()

,EmpID,EmpName,Email,Phone,Department
0,1001,Rohit Yadav,rohit.yadav1@example.com,9.111268e+09,Sales
1,1002,Meer Mehta,meera.mehta2@example.com,9.150787e+09,Operations
2,1003,Meer Mehta,kavya.rao3@example.com,9.310475e+09,Sales
3,1005,Sachin Joshi,sachin.joshi5@example.com,9.152289e+09,Operations
4,1006,Vikas Joshi,vikas.joshi6@example.com,9.775118e+08,Marketing
5,1008,Rahul Rao,rahul.rao8@example.com,9.918615e+09,Sales
6,1009,Nitin Iyer,nitin.iyer9@example.com,9.407051e+09,Marketing
7,1010,Sachin Shah,sachin.shah10@example.com,9.553605e+09,HR
8,1013,Neha Reddy,neha.reddy13@example.com,9.240042e+09,IT
9,1015,Neha Reddy,manoj.kapoor15@example.com,9.240042e+09,HR
10,1016,Amit Sharma,amit.sharma16@example.com,9.688355e+09,HR
11,1018,Deepak Shah,deepak.shah18@example.com,9.731236e+09,Sales
12,1020,Nitin Khan,nitin.khan20@example.com,9.899424e+09,HR
13,1021,Nitin Khan,karan.yadav21@example.com,9.737537e+09,Marketing
14,1022,Sachin Das,sachin.das22@example.com,9.666161e+09,IT
15,1023,Amit Yadav,amit.yadav23@example.com,9.980491e+09,Operations
16,1024,Arjun Mishra,arjun.mishra24@example.com,9.203299e+09,HR
17,1025,Meera Das,meera.das25@example.com,9.203299e+09,IT
18,1029,Priya Kulkarni,priya.kulkarni29@example.com,9.631158e+09,IT
19,1030,Rohit Mishra,rohit.mishra30@example.com,9.130307e+09,Marketing
20,1031,Rohit Mishra,arjun.yadav31@example.com,9.998462e+09,Marketing
21,1032,Nitin Mehta,nitin.mehta32@example.com,9.803409e+09,Marketing
22,1033,Ritika Rao,ritika.rao33@example.com,9.172254e+09,HR
23,1034,Nitin Gupta,nitin.gupta34@example.com,9.200346e+09,IT
24,1035,Nitin Gupta,nitin.gupta34@example.com,9.200346e+09,IT
25,1036,Nitin Gupta,nitin.gupta34@example.com,9.200346e+09,IT

In [38]:
cs.fillna("PYTHON",limit=2)

,EmpID,EmpName,Email,Phone,Department
0,1001,Rohit Yadav,rohit.yadav1@example.com,9111268039.0,Sales
1,1002,Meer Mehta,meera.mehta2@example.com,9150786963.0,Operations
2,1003,PYTHON,kavya.rao3@example.com,9310474687.0,Sales
3,1005,Sachin Joshi,sachin.joshi5@example.com,9152289378.0,Operations
4,1006,Vikas Joshi,vikas.joshi6@example.com,977511850.0,Marketing
5,1008,Rahul Rao,rahul.rao8@example.com,9918615372.0,Sales
6,1009,Nitin Iyer,nitin.iyer9@example.com,9407050929.0,Marketing
7,1010,Sachin Shah,sachin.shah10@example.com,9553605379.0,HR
8,1013,Neha Reddy,neha.reddy13@example.com,9240042131.0,IT
9,1015,PYTHON,manoj.kapoor15@example.com,PYTHON,HR
10,1016,Amit Sharma,amit.sharma16@example.com,9688355238.0,HR
11,1018,Deepak Shah,deepak.shah18@example.com,9731235606.0,Sales
12,1020,Nitin Khan,nitin.khan20@example.com,9899423617.0,HR
13,1021,NaN,karan.yadav21@example.com,9737537455.0,Marketing
14,1022,Sachin Das,sachin.das22@example.com,9666160764.0,IT
15,1023,Amit Yadav,amit.yadav23@example.com,9980490847.0,Operations
16,1024,Arjun Mishra,arjun.mishra24@example.com,9203299493.0,HR
17,1025,Meera Das,meera.das25@example.com,PYTHON,IT
18,1029,Priya Kulkarni,priya.kulkarni29@example.com,9631158426.0,PYTHON
19,1030,Rohit Mishra,rohit.mishra30@example.com,9130306846.0,Marketing
20,1031,NaN,arjun.yadav31@example.com,9998462204.0,Marketing
21,1032,Nitin Mehta,nitin.mehta32@example.com,9803408828.0,PYTHON
22,1033,Ritika Rao,ritika.rao33@example.com,9172253721.0,HR
23,1034,Nitin Gupta,nitin.gupta34@example.com,9200345531.0,IT
24,1035,NaN,PYTHON,NaN,NaN
25,1036,NaN,PYTHON,NaN,NaN