In [ ]:
#Insert

In [6]:
import pandas as pd

var = pd.DataFrame({"A":[1,2,3,4,5],"B":[6,7,8,9,0],"C":[21,22,23,42,43]})

var

   A  B   C
0  1  6  21
1  2  7  22
2  3  8  23
3  4  9  42
4  5  0  43

In [2]:
var.insert(1,"python",var["A"])
var

   A  python  B
0  1       1  6
1  2       2  7
2  3       3  8
3  4       4  9
4  5       5  0

In [3]:
var.insert(1,"python1",[11,12,13,14,15])
var

   A  python1  python  B
0  1       11       1  6
1  2       12       2  7
2  3       13       3  8
3  4       14       4  9
4  5       15       5  0

In [5]:
var["python12"] = var["A"][:2]
var

   A  python1  python  B  python12
0  1       11       1  6       1.0
1  2       12       2  7       2.0
2  3       13       3  8       NaN
3  4       14       4  9       NaN
4  5       15       5  0       NaN

In [ ]:
#Delete

In [7]:
var.pop("B")

0    6
1    7
2    8
3    9
4    0
Name: B, dtype: int64

In [8]:
var

   A   C
0  1  21
1  2  22
2  3  23
3  4  42
4  5  43

In [9]:
del var["A"]

In [10]:
var

    C
0  21
1  22
2  23
3  42
4  43