In [28]:
#Interpolate

In [29]:
import pandas as pd

cs = pd.read_csv(r"C:\Users\yadav\OneDrive\Desktop\Book2.csv")

cs

   ID   Age   Salary  Experience  Score
0   1  25.0  45000.0         2.0   80.0
1   2  28.0      NaN         4.0   85.0
2   3   NaN  55000.0         5.0   90.0
3   4  32.0  60000.0         NaN   95.0
4   5  35.0  65000.0         NaN    NaN
5   6   NaN  70000.0         NaN   98.0
6   7  40.0      NaN         NaN  100.0
7   8  42.0  80000.0         NaN   96.0
8   9  45.0  85000.0        12.0   94.0
9  10   NaN  90000.0        15.0   92.0

In [30]:
cs.interpolate

<bound method NDFrame.interpolate of    ID   Age   Salary  Experience  Score
0   1  25.0  45000.0         2.0   80.0
1   2  28.0      NaN         4.0   85.0
2   3   NaN  55000.0         5.0   90.0
3   4  32.0  60000.0         NaN   95.0
4   5  35.0  65000.0         NaN    NaN
5   6   NaN  70000.0         NaN   98.0
6   7  40.0      NaN         NaN  100.0
7   8  42.0  80000.0         NaN   96.0
8   9  45.0  85000.0        12.0   94.0
9  10   NaN  90000.0        15.0   92.0>

In [31]:

cs = cs.interpolate(
    method="linear",
    axis=0
)

In [32]:
cs.interpolate(method="linear",axis=1)

     ID   Age   Salary  Experience  Score
0   1.0  25.0  45000.0    2.000000   80.0
1   2.0  28.0  50000.0    4.000000   85.0
2   3.0  30.0  55000.0    5.000000   90.0
3   4.0  32.0  60000.0    6.166667   95.0
4   5.0  35.0  65000.0    7.333333   96.5
5   6.0  37.5  70000.0    8.500000   98.0
6   7.0  40.0  75000.0    9.666667  100.0
7   8.0  42.0  80000.0   10.833333   96.0
8   9.0  45.0  85000.0   12.000000   94.0
9  10.0  45.0  90000.0   15.000000   92.0

In [33]:
cs.interpolate(limit_direction="forward",limit=1)

   ID   Age   Salary  Experience  Score
0   1  25.0  45000.0    2.000000   80.0
1   2  28.0  50000.0    4.000000   85.0
2   3  30.0  55000.0    5.000000   90.0
3   4  32.0  60000.0    6.166667   95.0
4   5  35.0  65000.0    7.333333   96.5
5   6  37.5  70000.0    8.500000   98.0
6   7  40.0  75000.0    9.666667  100.0
7   8  42.0  80000.0   10.833333   96.0
8   9  45.0  85000.0   12.000000   94.0
9  10  45.0  90000.0   15.000000   92.0