In [32]:
#Join

In [33]:
import pandas as pd

var = pd.DataFrame({"A":[1,2,3,4],"B":[4,7,5,6]})
val = pd.DataFrame({"C":[21,22,23,24],"D":[11,22,33,44]})

var.join(val)

   A  B   C   D
0  1  4  21  11
1  2  7  22  22
2  3  5  23  33
3  4  6  24  44

In [34]:
import pandas as pd
print(pd.__version__)

3.0.5

In [35]:
import numpy as np
print(np.__version__)

2.5.1

In [36]:
va1 = pd.DataFrame({"A":[1,2,3,4],"B":[7,5,6,7]},index=['a','b','c','d'])
va2 = pd.DataFrame({"C":[21,22],"D":[11,22]},index=['a','b'])

va1.join(va2)

   A  B     C     D
a  1  7  21.0  11.0
b  2  5  22.0  22.0
c  3  6   NaN   NaN
d  4  7   NaN   NaN

In [37]:
va1.join(va2,how="cross")

   A  B   C   D
0  1  7  21  11
1  1  7  22  22
2  2  5  21  11
3  2  5  22  22
4  3  6  21  11
5  3  6  22  22
6  4  7  21  11
7  4  7  22  22

In [38]:
va1.join(va2,how="left")

   A  B     C     D
a  1  7  21.0  11.0
b  2  5  22.0  22.0
c  3  6   NaN   NaN
d  4  7   NaN   NaN

In [39]:
va1.join(va2,how="right")

   A  B   C   D
a  1  7  21  11
b  2  5  22  22

In [40]:
va1.join(va2,how="inner")

   A  B   C   D
a  1  7  21  11
b  2  5  22  22

In [45]:
va2.join(va1,how="outer",lsuffix="BR",rsuffix="BR")

      C     D  A  B_B
a  21.0  11.0  1    7
b  22.0  22.0  2    5
c   NaN   NaN  3    6
d   NaN   NaN  4    7

In [44]:
va1.rename(columns={"B": "B_B"}, inplace=True)
va1

   A  B_B
a  1    7
b  2    5
c  3    6
d  4    7