In [ ]:
#Merge

In [9]:
import pandas as pd

var = pd.DataFrame({"A":[1,2,3,4],"B":[4,7,5,6]})
val = pd.DataFrame({"A":[1,2,3,4],"C":[11,22,33,44]})

pd.merge(var,val,on="A")

   A  B   C
0  1  4  11
1  2  7  22
2  3  5  33
3  4  6  44

In [10]:
var = pd.DataFrame({"A":[1,2,3,4],"B":[4,7,5,6]})
val = pd.DataFrame({"A":[1,2,3,5],"C":[11,22,33,44]})

pd.merge(var,val,on="A")

   A  B   C
0  1  4  11
1  2  7  22
2  3  5  33

In [11]:
pd.merge(var,val,how="left")

   A  B     C
0  1  4  11.0
1  2  7  22.0
2  3  5  33.0
3  4  6   NaN

In [12]:
pd.merge(var,val,how="right")

   A    B   C
0  1  4.0  11
1  2  7.0  22
2  3  5.0  33
3  5  NaN  44

In [13]:
pd.merge(var,val,how="cross")

    A_x  B  A_y   C
0     1  4    1  11
1     1  4    2  22
2     1  4    3  33
3     1  4    5  44
4     2  7    1  11
5     2  7    2  22
6     2  7    3  33
7     2  7    5  44
8     3  5    1  11
9     3  5    2  22
10    3  5    3  33
11    3  5    5  44
12    4  6    1  11
13    4  6    2  22
14    4  6    3  33
15    4  6    5  44

In [14]:
pd.merge(var,val,how="inner")

   A  B   C
0  1  4  11
1  2  7  22
2  3  5  33

In [15]:
pd.merge(var,val,how="outer")

   A    B     C
0  1  4.0  11.0
1  2  7.0  22.0
2  3  5.0  33.0
3  4  6.0   NaN
4  5  NaN  44.0

In [16]:
pd.merge(var,val,how="left_anti")

   A  B   C
3  4  6 NaN

In [17]:
pd.merge(var,val,how="right_anti")

   A   B   C
3  5 NaN  44

In [19]:
pd.merge(var,val,left_index=True,right_index=True)

   A_x  B  A_y   C
0    1  4    1  11
1    2  7    2  22
2    3  5    3  33
3    4  6    5  44

In [20]:
pd.merge(var,val,left_index=True,right_index=True,suffixes=("name","python"))

   Aname  B  Apython   C
0      1  4        1  11
1      2  7        2  22
2      3  5        3  33
3      4  6        5  44

In [21]:
#Concat

In [22]:
sr = pd.Series([1,2,3,4])
cr = pd.Series([11,22,33,44])
pd.concat([sr,cr])

0     1
1     2
2     3
3     4
0    11
1    22
2    33
3    44
dtype: int64

In [24]:
va1 = pd.DataFrame({"A":[1,2,3,4],"B":[4,7,5,6]})
va2 = pd.DataFrame({"A":[1,2,3,4],"B":[11,22,33,44]})
pd.concat([va1,va2])

   A   B
0  1   4
1  2   7
2  3   5
3  4   6
0  1  11
1  2  22
2  3  33
3  4  44

In [25]:
va1 = pd.DataFrame({"A":[1,2,3,4],"B":[4,7,5,6]})
va2 = pd.DataFrame({"A":[1,2,3,4],"C":[11,22,33,44]})
pd.concat([va1,va2])

   A    B     C
0  1  4.0   NaN
1  2  7.0   NaN
2  3  5.0   NaN
3  4  6.0   NaN
0  1  NaN  11.0
1  2  NaN  22.0
2  3  NaN  33.0
3  4  NaN  44.0

In [29]:
pd.concat([va1, va2],axis=1)

   A  B  A   C
0  1  4  1  11
1  2  7  2  22
2  3  5  3  33
3  4  6  4  44

In [30]:
pd.concat([va1, va2],axis=1,join="outer")

   A  B  A   C
0  1  4  1  11
1  2  7  2  22
2  3  5  3  33
3  4  6  4  44

In [33]:
pd.concat([va1, va2],axis=1,keys=["va1","va2"])

  va1    va2
    A  B   A   C
0   1  4   1  11
1   2  7   2  22
2   3  5   3  33
3   4  6   4  44