In [ ]:
#Melt Function

In [1]:
import pandas as pd

var = pd.DataFrame({
    "Days":[1,2,3,4,5],
    "Eng":[12,13,14,15,15],
    "Math":[21,3,2,43,21]
})
var

   Days  Eng  Math
0     1   12    21
1     2   13     3
2     3   14     2
3     4   15    43
4     5   15    21

In [4]:
pd.melt(var)

   variable  value
0      Days      1
1      Days      2
2      Days      3
3      Days      4
4      Days      5
5       Eng     12
6       Eng     13
7       Eng     14
8       Eng     15
9       Eng     15
10     Math     21
11     Math      3
12     Math      2
13     Math     43
14     Math     21

In [5]:
pd.melt(var,id_vars=["Math"])

   Math variable  value
0    21     Days      1
1     3     Days      2
2     2     Days      3
3    43     Days      4
4    21     Days      5
5    21      Eng     12
6     3      Eng     13
7     2      Eng     14
8    43      Eng     15
9    21      Eng     15

In [6]:
pd.melt(var,id_vars=["Days"])

   Days variable  value
0     1      Eng     12
1     2      Eng     13
2     3      Eng     14
3     4      Eng     15
4     5      Eng     15
5     1     Math     21
6     2     Math      3
7     3     Math      2
8     4     Math     43
9     5     Math     21

In [8]:
pd.melt(var,id_vars=["Days"],var_name="Nitu")

   Days  Nitu  value
0     1   Eng     12
1     2   Eng     13
2     3   Eng     14
3     4   Eng     15
4     5   Eng     15
5     1  Math     21
6     2  Math      3
7     3  Math      2
8     4  Math     43
9     5  Math     21

In [10]:
pd.melt(var,id_vars=["Days"],var_name="IIII",value_name="OOOO")

   Days  IIII  OOOO
0     1   Eng    12
1     2   Eng    13
2     3   Eng    14
3     4   Eng    15
4     5   Eng    15
5     1  Math    21
6     2  Math     3
7     3  Math     2
8     4  Math    43
9     5  Math    21

In [1]:
#Pivot Table

In [12]:
cr = pd.DataFrame({
    "Days":[1,2,3,4,5],
    "stu":['a','b','c','d','e'],
    "Eng":[12,13,14,15,15],
    "Math":[21,3,2,43,21]
})
cr

   Days stu  Eng  Math
0     1   a   12    21
1     2   b   13     3
2     3   c   14     2
3     4   d   15    43
4     5   e   15    21

In [14]:
cr.pivot(index="Days",columns="stu")

       Eng                          Math
stu      a     b     c     d     e     a    b    c     d     e
Days
1     12.0   NaN   NaN   NaN   NaN  21.0  NaN  NaN   NaN   NaN
2      NaN  13.0   NaN   NaN   NaN   NaN  3.0  NaN   NaN   NaN
3      NaN   NaN  14.0   NaN   NaN   NaN  NaN  2.0   NaN   NaN
4      NaN   NaN   NaN  15.0   NaN   NaN  NaN  NaN  43.0   NaN
5      NaN   NaN   NaN   NaN  15.0   NaN  NaN  NaN   NaN  21.0

In [15]:
sr = pd.DataFrame({
    "Days":[1,2,3,4,5],
    "stu":['a','a','c','c','e'],
    "Eng":[12,13,14,15,15],
    "Math":[21,3,2,43,21]
})
sr

   Days stu  Eng  Math
0     1   a   12    21
1     2   a   13     3
2     3   c   14     2
3     4   c   15    43
4     5   e   15    21

In [16]:
sr.pivot(index="Days",columns="stu")

       Eng              Math
stu      a     c     e     a     c     e
Days
1     12.0   NaN   NaN  21.0   NaN   NaN
2     13.0   NaN   NaN   3.0   NaN   NaN
3      NaN  14.0   NaN   NaN   2.0   NaN
4      NaN  15.0   NaN   NaN  43.0   NaN
5      NaN   NaN  15.0   NaN   NaN  21.0

In [17]:
sr.pivot(index="Days",columns="stu",values="Eng")

stu      a     c     e
Days
1     12.0   NaN   NaN
2     13.0   NaN   NaN
3      NaN  14.0   NaN
4      NaN  15.0   NaN
5      NaN   NaN  15.0

In [ ]:
sr.pivot(index="Days",columns="stu")

In [21]:
mr = pd.DataFrame({
    "Days":[1,1,2,1,2],
    "stu":['a','a','c','c','e'],
    "Eng":[12,13,14,15,15],
    "Math":[21,3,2,43,21]
})
mr

   Days stu  Eng  Math
0     1   a   12    21
1     1   a   13     3
2     2   c   14     2
3     1   c   15    43
4     2   e   15    21

In [22]:
mr.pivot_table(index="stu",columns="Days",aggfunc="mean")

       Eng        Math
Days     1     2     1     2
stu
a     12.5   NaN  12.0   NaN
c     15.0  14.0  43.0   2.0
e      NaN  15.0   NaN  21.0

In [23]:
mr.pivot_table(index="stu",columns="Days",aggfunc="sum")

       Eng        Math
Days     1     2     1     2
stu
a     25.0   NaN  24.0   NaN
c     15.0  14.0  43.0   2.0
e      NaN  15.0   NaN  21.0

In [26]:
mr.pivot_table(index="stu",columns="Days",aggfunc="median",margins=True)

       Eng              Math
Days     1     2   All     1     2   All
stu
a     12.5   NaN  12.5  12.0   NaN  12.0
c     15.0  14.0  14.5  43.0   2.0  22.5
e      NaN  15.0  15.0   NaN  21.0  21.0
All   13.0  14.5  14.0  21.0  11.5  21.0