In [19]:
#Read CSV File

In [20]:
import pandas as pd

csv1 = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv")

csv1

    CustomerID CustomerName  Country        State       City
0         1001   Customer_1  Germany   California     Austin
1         1002   Customer_2       UK   California  Bangalore
2         1003   Customer_3       UK  Maharashtra  Bangalore
3         1004   Customer_4      USA  Maharashtra     Mumbai
4         1005   Customer_5  Germany    Karnataka     Mumbai
5         1006   Customer_6    India        Texas     London
6         1007   Customer_7      USA      Bavaria     Munich
7         1008   Customer_8  Germany        Texas     London
8         1009   Customer_9    India        Texas     Munich
9         1010  Customer_10       UK        Texas     Munich
10        1011  Customer_11       UK        Texas     Austin
11        1012  Customer_12       UK   California     Austin
12        1013  Customer_13      USA  Maharashtra     Munich
13        1014  Customer_14      USA    Karnataka     London
14        1015  Customer_15      USA    Karnataka     London
15        1016  Customer_16    India   California     Mumbai
16        1017  Customer_17      USA        Texas       Pune
17        1018  Customer_18       UK      Bavaria     Austin
18        1019  Customer_19    India   California  Bangalore
19        1020  Customer_20    India        Texas  Bangalore
20        1021  Customer_21  Germany    Karnataka     London
21        1022  Customer_22       UK      Bavaria     Austin
22        1023  Customer_23  Germany      Bavaria  Bangalore
23        1024  Customer_24       UK  Maharashtra     Mumbai
24        1025  Customer_25    India   California     Austin
25        1026  Customer_26  Germany      Bavaria     Austin
26        1027  Customer_27    India    Karnataka     Austin
27        1028  Customer_28       UK       London     Munich
28        1029  Customer_29  Germany   California     London
29        1030  Customer_30    India   California     Munich
30        1031  Customer_31       UK        Texas  Bangalore
31        1032  Customer_32      USA        Texas       Pune
32        1033  Customer_33    India       London     London
33        1034  Customer_34       UK      Bavaria     Munich
34        1035  Customer_35    India       London     Munich
35        1036  Customer_36    India    Karnataka       Pune
36        1037  Customer_37       UK        Texas     Austin
37        1038  Customer_38  Germany      Bavaria  Bangalore
38        1039  Customer_39  Germany   California       Pune
39        1040  Customer_40      USA   California       Pune
40        1041  Customer_41  Germany       London       Pune
41        1042  Customer_42  Germany    Karnataka     Munich
42        1043  Customer_43      USA        Texas     Mumbai
43        1044  Customer_44  Germany      Bavaria     Mumbai
44        1045  Customer_45    India    Karnataka     London
45        1046  Customer_46  Germany        Texas     Mumbai
46        1047  Customer_47      USA   California  Bangalore
47        1048  Customer_48  Germany  Maharashtra  Bangalore
48        1049  Customer_49  Germany   California     London
49        1050  Customer_50       UK   California     Austin

In [21]:
csv2 = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv",nrows=1)

csv2

   CustomerID CustomerName  Country       State    City
0        1001   Customer_1  Germany  California  Austin

In [22]:
csv3 = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv",usecols=["CustomerID"])

csv3

    CustomerID
0         1001
1         1002
2         1003
3         1004
4         1005
5         1006
6         1007
7         1008
8         1009
9         1010
10        1011
11        1012
12        1013
13        1014
14        1015
15        1016
16        1017
17        1018
18        1019
19        1020
20        1021
21        1022
22        1023
23        1024
24        1025
25        1026
26        1027
27        1028
28        1029
29        1030
30        1031
31        1032
32        1033
33        1034
34        1035
35        1036
36        1037
37        1038
38        1039
39        1040
40        1041
41        1042
42        1043
43        1044
44        1045
45        1046
46        1047
47        1048
48        1049
49        1050

In [23]:
csv4 = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv",usecols=[0,1])

csv4

    CustomerID CustomerName
0         1001   Customer_1
1         1002   Customer_2
2         1003   Customer_3
3         1004   Customer_4
4         1005   Customer_5
5         1006   Customer_6
6         1007   Customer_7
7         1008   Customer_8
8         1009   Customer_9
9         1010  Customer_10
10        1011  Customer_11
11        1012  Customer_12
12        1013  Customer_13
13        1014  Customer_14
14        1015  Customer_15
15        1016  Customer_16
16        1017  Customer_17
17        1018  Customer_18
18        1019  Customer_19
19        1020  Customer_20
20        1021  Customer_21
21        1022  Customer_22
22        1023  Customer_23
23        1024  Customer_24
24        1025  Customer_25
25        1026  Customer_26
26        1027  Customer_27
27        1028  Customer_28
28        1029  Customer_29
29        1030  Customer_30
30        1031  Customer_31
31        1032  Customer_32
32        1033  Customer_33
33        1034  Customer_34
34        1035  Customer_35
35        1036  Customer_36
36        1037  Customer_37
37        1038  Customer_38
38        1039  Customer_39
39        1040  Customer_40
40        1041  Customer_41
41        1042  Customer_42
42        1043  Customer_43
43        1044  Customer_44
44        1045  Customer_45
45        1046  Customer_46
46        1047  Customer_47
47        1048  Customer_48
48        1049  Customer_49
49        1050  Customer_50

In [24]:
csv5 = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv",skiprows=[1,3,2,4,6,49])

csv5

    CustomerID CustomerName  Country        State       City
0         1005   Customer_5  Germany    Karnataka     Mumbai
1         1007   Customer_7      USA      Bavaria     Munich
2         1008   Customer_8  Germany        Texas     London
3         1009   Customer_9    India        Texas     Munich
4         1010  Customer_10       UK        Texas     Munich
5         1011  Customer_11       UK        Texas     Austin
6         1012  Customer_12       UK   California     Austin
7         1013  Customer_13      USA  Maharashtra     Munich
8         1014  Customer_14      USA    Karnataka     London
9         1015  Customer_15      USA    Karnataka     London
10        1016  Customer_16    India   California     Mumbai
11        1017  Customer_17      USA        Texas       Pune
12        1018  Customer_18       UK      Bavaria     Austin
13        1019  Customer_19    India   California  Bangalore
14        1020  Customer_20    India        Texas  Bangalore
15        1021  Customer_21  Germany    Karnataka     London
16        1022  Customer_22       UK      Bavaria     Austin
17        1023  Customer_23  Germany      Bavaria  Bangalore
18        1024  Customer_24       UK  Maharashtra     Mumbai
19        1025  Customer_25    India   California     Austin
20        1026  Customer_26  Germany      Bavaria     Austin
21        1027  Customer_27    India    Karnataka     Austin
22        1028  Customer_28       UK       London     Munich
23        1029  Customer_29  Germany   California     London
24        1030  Customer_30    India   California     Munich
25        1031  Customer_31       UK        Texas  Bangalore
26        1032  Customer_32      USA        Texas       Pune
27        1033  Customer_33    India       London     London
28        1034  Customer_34       UK      Bavaria     Munich
29        1035  Customer_35    India       London     Munich
30        1036  Customer_36    India    Karnataka       Pune
31        1037  Customer_37       UK        Texas     Austin
32        1038  Customer_38  Germany      Bavaria  Bangalore
33        1039  Customer_39  Germany   California       Pune
34        1040  Customer_40      USA   California       Pune
35        1041  Customer_41  Germany       London       Pune
36        1042  Customer_42  Germany    Karnataka     Munich
37        1043  Customer_43      USA        Texas     Mumbai
38        1044  Customer_44  Germany      Bavaria     Mumbai
39        1045  Customer_45    India    Karnataka     London
40        1046  Customer_46  Germany        Texas     Mumbai
41        1047  Customer_47      USA   California  Bangalore
42        1048  Customer_48  Germany  Maharashtra  Bangalore
43        1050  Customer_50       UK   California     Austin

In [25]:
csv6 = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv",index_col="CustomerID")

csv6

           CustomerName  Country        State       City
CustomerID
1001         Customer_1  Germany   California     Austin
1002         Customer_2       UK   California  Bangalore
1003         Customer_3       UK  Maharashtra  Bangalore
1004         Customer_4      USA  Maharashtra     Mumbai
1005         Customer_5  Germany    Karnataka     Mumbai
1006         Customer_6    India        Texas     London
1007         Customer_7      USA      Bavaria     Munich
1008         Customer_8  Germany        Texas     London
1009         Customer_9    India        Texas     Munich
1010        Customer_10       UK        Texas     Munich
1011        Customer_11       UK        Texas     Austin
1012        Customer_12       UK   California     Austin
1013        Customer_13      USA  Maharashtra     Munich
1014        Customer_14      USA    Karnataka     London
1015        Customer_15      USA    Karnataka     London
1016        Customer_16    India   California     Mumbai
1017        Customer_17      USA        Texas       Pune
1018        Customer_18       UK      Bavaria     Austin
1019        Customer_19    India   California  Bangalore
1020        Customer_20    India        Texas  Bangalore
1021        Customer_21  Germany    Karnataka     London
1022        Customer_22       UK      Bavaria     Austin
1023        Customer_23  Germany      Bavaria  Bangalore
1024        Customer_24       UK  Maharashtra     Mumbai
1025        Customer_25    India   California     Austin
1026        Customer_26  Germany      Bavaria     Austin
1027        Customer_27    India    Karnataka     Austin
1028        Customer_28       UK       London     Munich
1029        Customer_29  Germany   California     London
1030        Customer_30    India   California     Munich
1031        Customer_31       UK        Texas  Bangalore
1032        Customer_32      USA        Texas       Pune
1033        Customer_33    India       London     London
1034        Customer_34       UK      Bavaria     Munich
1035        Customer_35    India       London     Munich
1036        Customer_36    India    Karnataka       Pune
1037        Customer_37       UK        Texas     Austin
1038        Customer_38  Germany      Bavaria  Bangalore
1039        Customer_39  Germany   California       Pune
1040        Customer_40      USA   California       Pune
1041        Customer_41  Germany       London       Pune
1042        Customer_42  Germany    Karnataka     Munich
1043        Customer_43      USA        Texas     Mumbai
1044        Customer_44  Germany      Bavaria     Mumbai
1045        Customer_45    India    Karnataka     London
1046        Customer_46  Germany        Texas     Mumbai
1047        Customer_47      USA   California  Bangalore
1048        Customer_48  Germany  Maharashtra  Bangalore
1049        Customer_49  Germany   California     London
1050        Customer_50       UK   California     Austin

In [26]:
csv7 = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv",header=33)

csv7

    1033  Customer_33    India       London   London.1
0   1034  Customer_34       UK      Bavaria     Munich
1   1035  Customer_35    India       London     Munich
2   1036  Customer_36    India    Karnataka       Pune
3   1037  Customer_37       UK        Texas     Austin
4   1038  Customer_38  Germany      Bavaria  Bangalore
5   1039  Customer_39  Germany   California       Pune
6   1040  Customer_40      USA   California       Pune
7   1041  Customer_41  Germany       London       Pune
8   1042  Customer_42  Germany    Karnataka     Munich
9   1043  Customer_43      USA        Texas     Mumbai
10  1044  Customer_44  Germany      Bavaria     Mumbai
11  1045  Customer_45    India    Karnataka     London
12  1046  Customer_46  Germany        Texas     Mumbai
13  1047  Customer_47      USA   California  Bangalore
14  1048  Customer_48  Germany  Maharashtra  Bangalore
15  1049  Customer_49  Germany   California     London
16  1050  Customer_50       UK   California     Austin

In [27]:
csv8 = pd.read_csv(r"C:\Users\yadav\Downloads\Customers (2).csv",names=["A","B","C","D","E"])

csv8

             A             B        C            D          E
0   CustomerID  CustomerName  Country        State       City
1         1001    Customer_1  Germany   California     Austin
2         1002    Customer_2       UK   California  Bangalore
3         1003    Customer_3       UK  Maharashtra  Bangalore
4         1004    Customer_4      USA  Maharashtra     Mumbai
5         1005    Customer_5  Germany    Karnataka     Mumbai
6         1006    Customer_6    India        Texas     London
7         1007    Customer_7      USA      Bavaria     Munich
8         1008    Customer_8  Germany        Texas     London
9         1009    Customer_9    India        Texas     Munich
10        1010   Customer_10       UK        Texas     Munich
11        1011   Customer_11       UK        Texas     Austin
12        1012   Customer_12       UK   California     Austin
13        1013   Customer_13      USA  Maharashtra     Munich
14        1014   Customer_14      USA    Karnataka     London
15        1015   Customer_15      USA    Karnataka     London
16        1016   Customer_16    India   California     Mumbai
17        1017   Customer_17      USA        Texas       Pune
18        1018   Customer_18       UK      Bavaria     Austin
19        1019   Customer_19    India   California  Bangalore
20        1020   Customer_20    India        Texas  Bangalore
21        1021   Customer_21  Germany    Karnataka     London
22        1022   Customer_22       UK      Bavaria     Austin
23        1023   Customer_23  Germany      Bavaria  Bangalore
24        1024   Customer_24       UK  Maharashtra     Mumbai
25        1025   Customer_25    India   California     Austin
26        1026   Customer_26  Germany      Bavaria     Austin
27        1027   Customer_27    India    Karnataka     Austin
28        1028   Customer_28       UK       London     Munich
29        1029   Customer_29  Germany   California     London
30        1030   Customer_30    India   California     Munich
31        1031   Customer_31       UK        Texas  Bangalore
32        1032   Customer_32      USA        Texas       Pune
33        1033   Customer_33    India       London     London
34        1034   Customer_34       UK      Bavaria     Munich
35        1035   Customer_35    India       London     Munich
36        1036   Customer_36    India    Karnataka       Pune
37        1037   Customer_37       UK        Texas     Austin
38        1038   Customer_38  Germany      Bavaria  Bangalore
39        1039   Customer_39  Germany   California       Pune
40        1040   Customer_40      USA   California       Pune
41        1041   Customer_41  Germany       London       Pune
42        1042   Customer_42  Germany    Karnataka     Munich
43        1043   Customer_43      USA        Texas     Mumbai
44        1044   Customer_44  Germany      Bavaria     Mumbai
45        1045   Customer_45    India    Karnataka     London
46        1046   Customer_46  Germany        Texas     Mumbai
47        1047   Customer_47      USA   California  Bangalore
48        1048   Customer_48  Germany  Maharashtra  Bangalore
49        1049   Customer_49  Germany   California     London
50        1050   Customer_50       UK   California     Austin

In [31]:
cs = pd.read_csv(r"D:\AI-ML\Pandas\nitu.csv",header = None)

cs

   0  1  2
0  0  1  6
1  1  2  7
2  2  3  8
3  3  4  9
4  4  5  0

In [32]:
cs1 = pd.read_csv(r"D:\AI-ML\Pandas\nitu.csv",header = None,names=["col1","col2","col3"])

cs1

   col1  col2  col3
0     0     1     6
1     1     2     7
2     2     3     8
3     3     4     9
4     4     5     0

In [33]:
cs2 = pd.read_csv(r"D:\AI-ML\Pandas\nitu.csv",header = None,names=["col1","col2","col3"],dtype={"col2":"float"})

cs2

   col1  col2  col3
0     0   1.0     6
1     1   2.0     7
2     2   3.0     8
3     3   4.0     9
4     4   5.0     0