In [ ]:
#Replace

In [ ]:
import pandas as pd

cs = pd.read_csv(r"C:\Users\yadav\OneDrive\Desktop\Documents\Book1.csv")

cs

,EmpID,EmpName,Email,Phone,Department
0,1001,Rohit Yadav,rohit.yadav1@example.com,9.111268e+09,Sales
1,1002,Meer Mehta,meera.mehta2@example.com,9.150787e+09,Operations
2,1003,NaN,kavya.rao3@example.com,9.310475e+09,Sales
3,1005,Sachin Joshi,sachin.joshi5@example.com,9.152289e+09,Operations
4,1006,Vikas Joshi,vikas.joshi6@example.com,9.775118e+08,Marketing
5,1008,Rahul Rao,rahul.rao8@example.com,9.918615e+09,Sales
6,1009,Nitin Iyer,nitin.iyer9@example.com,9.407051e+09,Marketing
7,1010,Sachin Shah,sachin.shah10@example.com,9.553605e+09,HR
8,1013,Neha Reddy,neha.reddy13@example.com,9.240042e+09,IT
9,1015,NaN,manoj.kapoor15@example.com,NaN,HR
10,1016,Amit Sharma,amit.sharma16@example.com,9.688355e+09,HR
11,1018,Deepak Shah,deepak.shah18@example.com,9.731236e+09,Sales
12,1020,Nitin Khan,nitin.khan20@example.com,9.899424e+09,HR
13,1021,NaN,karan.yadav21@example.com,9.737537e+09,Marketing
14,1022,Sachin Das,sachin.das22@example.com,9.666161e+09,IT
15,1023,Amit Yadav,amit.yadav23@example.com,9.980491e+09,Operations
16,1024,Arjun Mishra,arjun.mishra24@example.com,9.203299e+09,HR
17,1025,Meera Das,meera.das25@example.com,NaN,IT
18,1029,Priya Kulkarni,priya.kulkarni29@example.com,9.631158e+09,NaN
19,1030,Rohit Mishra,rohit.mishra30@example.com,9.130307e+09,Marketing
20,1031,NaN,arjun.yadav31@example.com,9.998462e+09,Marketing
21,1032,Nitin Mehta,nitin.mehta32@example.com,9.803409e+09,NaN
22,1033,Ritika Rao,ritika.rao33@example.com,9.172254e+09,HR
23,1034,Nitin Gupta,nitin.gupta34@example.com,9.200346e+09,IT
24,1035,NaN,NaN,NaN,NaN
25,1036,NaN,NaN,NaN,NaN

In [3]:
cs.replace(to_replace= "Rohit Yadav",value="PYTHON")

,EmpID,EmpName,Email,Phone,Department
0,1001,PYTHON,rohit.yadav1@example.com,9.111268e+09,Sales
1,1002,Meer Mehta,meera.mehta2@example.com,9.150787e+09,Operations
2,1003,NaN,kavya.rao3@example.com,9.310475e+09,Sales
3,1005,Sachin Joshi,sachin.joshi5@example.com,9.152289e+09,Operations
4,1006,Vikas Joshi,vikas.joshi6@example.com,9.775118e+08,Marketing
5,1008,Rahul Rao,rahul.rao8@example.com,9.918615e+09,Sales
6,1009,Nitin Iyer,nitin.iyer9@example.com,9.407051e+09,Marketing
7,1010,Sachin Shah,sachin.shah10@example.com,9.553605e+09,HR
8,1013,Neha Reddy,neha.reddy13@example.com,9.240042e+09,IT
9,1015,NaN,manoj.kapoor15@example.com,NaN,HR
10,1016,Amit Sharma,amit.sharma16@example.com,9.688355e+09,HR
11,1018,Deepak Shah,deepak.shah18@example.com,9.731236e+09,Sales
12,1020,Nitin Khan,nitin.khan20@example.com,9.899424e+09,HR
13,1021,NaN,karan.yadav21@example.com,9.737537e+09,Marketing
14,1022,Sachin Das,sachin.das22@example.com,9.666161e+09,IT
15,1023,Amit Yadav,amit.yadav23@example.com,9.980491e+09,Operations
16,1024,Arjun Mishra,arjun.mishra24@example.com,9.203299e+09,HR
17,1025,Meera Das,meera.das25@example.com,NaN,IT
18,1029,Priya Kulkarni,priya.kulkarni29@example.com,9.631158e+09,NaN
19,1030,Rohit Mishra,rohit.mishra30@example.com,9.130307e+09,Marketing
20,1031,NaN,arjun.yadav31@example.com,9.998462e+09,Marketing
21,1032,Nitin Mehta,nitin.mehta32@example.com,9.803409e+09,NaN
22,1033,Ritika Rao,ritika.rao33@example.com,9.172254e+09,HR
23,1034,Nitin Gupta,nitin.gupta34@example.com,9.200346e+09,IT
24,1035,NaN,NaN,NaN,NaN
25,1036,NaN,NaN,NaN,NaN

In [5]:
cs.replace([1001,1002,1003,1004,1005,1006,1007,1008,1009,1010],101)

,EmpID,EmpName,Email,Phone,Department
0,101,Rohit Yadav,rohit.yadav1@example.com,9.111268e+09,Sales
1,101,Meer Mehta,meera.mehta2@example.com,9.150787e+09,Operations
2,101,NaN,kavya.rao3@example.com,9.310475e+09,Sales
3,101,Sachin Joshi,sachin.joshi5@example.com,9.152289e+09,Operations
4,101,Vikas Joshi,vikas.joshi6@example.com,9.775118e+08,Marketing
5,101,Rahul Rao,rahul.rao8@example.com,9.918615e+09,Sales
6,101,Nitin Iyer,nitin.iyer9@example.com,9.407051e+09,Marketing
7,101,Sachin Shah,sachin.shah10@example.com,9.553605e+09,HR
8,1013,Neha Reddy,neha.reddy13@example.com,9.240042e+09,IT
9,1015,NaN,manoj.kapoor15@example.com,NaN,HR
10,1016,Amit Sharma,amit.sharma16@example.com,9.688355e+09,HR
11,1018,Deepak Shah,deepak.shah18@example.com,9.731236e+09,Sales
12,1020,Nitin Khan,nitin.khan20@example.com,9.899424e+09,HR
13,1021,NaN,karan.yadav21@example.com,9.737537e+09,Marketing
14,1022,Sachin Das,sachin.das22@example.com,9.666161e+09,IT
15,1023,Amit Yadav,amit.yadav23@example.com,9.980491e+09,Operations
16,1024,Arjun Mishra,arjun.mishra24@example.com,9.203299e+09,HR
17,1025,Meera Das,meera.das25@example.com,NaN,IT
18,1029,Priya Kulkarni,priya.kulkarni29@example.com,9.631158e+09,NaN
19,1030,Rohit Mishra,rohit.mishra30@example.com,9.130307e+09,Marketing
20,1031,NaN,arjun.yadav31@example.com,9.998462e+09,Marketing
21,1032,Nitin Mehta,nitin.mehta32@example.com,9.803409e+09,NaN
22,1033,Ritika Rao,ritika.rao33@example.com,9.172254e+09,HR
23,1034,Nitin Gupta,nitin.gupta34@example.com,9.200346e+09,IT
24,1035,NaN,NaN,NaN,NaN
25,1036,NaN,NaN,NaN,NaN

In [7]:
cs.replace("[A-Z]","PYTHON",regex=True)

,EmpID,EmpName,Email,Phone,Department
0,1001,PYTHONohit PYTHONadav,rohit.yadav1@example.com,9.111268e+09,PYTHONales
1,1002,PYTHONeer PYTHONehta,meera.mehta2@example.com,9.150787e+09,PYTHONperations
2,1003,NaN,kavya.rao3@example.com,9.310475e+09,PYTHONales
3,1005,PYTHONachin PYTHONoshi,sachin.joshi5@example.com,9.152289e+09,PYTHONperations
4,1006,PYTHONikas PYTHONoshi,vikas.joshi6@example.com,9.775118e+08,PYTHONarketing
5,1008,PYTHONahul PYTHONao,rahul.rao8@example.com,9.918615e+09,PYTHONales
6,1009,PYTHONitin PYTHONyer,nitin.iyer9@example.com,9.407051e+09,PYTHONarketing
7,1010,PYTHONachin PYTHONhah,sachin.shah10@example.com,9.553605e+09,PYTHONPYTHON
8,1013,PYTHONeha PYTHONeddy,neha.reddy13@example.com,9.240042e+09,PYTHONPYTHON
9,1015,NaN,manoj.kapoor15@example.com,NaN,PYTHONPYTHON
10,1016,PYTHONmit PYTHONharma,amit.sharma16@example.com,9.688355e+09,PYTHONPYTHON
11,1018,PYTHONeepak PYTHONhah,deepak.shah18@example.com,9.731236e+09,PYTHONales
12,1020,PYTHONitin PYTHONhan,nitin.khan20@example.com,9.899424e+09,PYTHONPYTHON
13,1021,NaN,karan.yadav21@example.com,9.737537e+09,PYTHONarketing
14,1022,PYTHONachin PYTHONas,sachin.das22@example.com,9.666161e+09,PYTHONPYTHON
15,1023,PYTHONmit PYTHONadav,amit.yadav23@example.com,9.980491e+09,PYTHONperations
16,1024,PYTHONrjun PYTHONishra,arjun.mishra24@example.com,9.203299e+09,PYTHONPYTHON
17,1025,PYTHONeera PYTHONas,meera.das25@example.com,NaN,PYTHONPYTHON
18,1029,PYTHONriya PYTHONulkarni,priya.kulkarni29@example.com,9.631158e+09,NaN
19,1030,PYTHONohit PYTHONishra,rohit.mishra30@example.com,9.130307e+09,PYTHONarketing
20,1031,NaN,arjun.yadav31@example.com,9.998462e+09,PYTHONarketing
21,1032,PYTHONitin PYTHONehta,nitin.mehta32@example.com,9.803409e+09,NaN
22,1033,PYTHONitika PYTHONao,ritika.rao33@example.com,9.172254e+09,PYTHONPYTHON
23,1034,PYTHONitin PYTHONupta,nitin.gupta34@example.com,9.200346e+09,PYTHONPYTHON
24,1035,NaN,NaN,NaN,NaN
25,1036,NaN,NaN,NaN,NaN

In [ ]:
cs.replace(1,f)

,EmpID,EmpName,Email,Phone,Department
0,1001,Rohit Yadav,rohit.yadav1@example.com,9.111268e+09,Sales
1,1002,Meer Mehta,meera.mehta2@example.com,9.150787e+09,Operations
2,1003,NaN,kavya.rao3@example.com,9.310475e+09,Sales
3,1005,Sachin Joshi,sachin.joshi5@example.com,9.152289e+09,Operations
4,1006,Vikas Joshi,vikas.joshi6@example.com,9.775118e+08,Marketing
5,1008,Rahul Rao,rahul.rao8@example.com,9.918615e+09,Sales
6,1009,Nitin Iyer,nitin.iyer9@example.com,9.407051e+09,Marketing
7,1010,Sachin Shah,sachin.shah10@example.com,9.553605e+09,HR
8,1013,Neha Reddy,neha.reddy13@example.com,9.240042e+09,IT
9,1015,NaN,manoj.kapoor15@example.com,NaN,HR
10,1016,Amit Sharma,amit.sharma16@example.com,9.688355e+09,HR
11,1018,Deepak Shah,deepak.shah18@example.com,9.731236e+09,Sales
12,1020,Nitin Khan,nitin.khan20@example.com,9.899424e+09,HR
13,1021,NaN,karan.yadav21@example.com,9.737537e+09,Marketing
14,1022,Sachin Das,sachin.das22@example.com,9.666161e+09,IT
15,1023,Amit Yadav,amit.yadav23@example.com,9.980491e+09,Operations
16,1024,Arjun Mishra,arjun.mishra24@example.com,9.203299e+09,HR
17,1025,Meera Das,meera.das25@example.com,NaN,IT
18,1029,Priya Kulkarni,priya.kulkarni29@example.com,9.631158e+09,NaN
19,1030,Rohit Mishra,rohit.mishra30@example.com,9.130307e+09,Marketing
20,1031,NaN,arjun.yadav31@example.com,9.998462e+09,Marketing
21,1032,Nitin Mehta,nitin.mehta32@example.com,9.803409e+09,NaN
22,1033,Ritika Rao,ritika.rao33@example.com,9.172254e+09,HR
23,1034,Nitin Gupta,nitin.gupta34@example.com,9.200346e+09,IT
24,1035,NaN,NaN,NaN,NaN
25,1036,NaN,NaN,NaN,NaN

In [20]:
import numpy as np

cs = cs.replace(1, np.nan)
cs = cs.ffill()
cs.head()

   EmpID       EmpName                      Email         Phone  Department
0   1001   Rohit Yadav   rohit.yadav1@example.com  9.111268e+09       Sales
1   1002    Meer Mehta   meera.mehta2@example.com  9.150787e+09  Operations
2   1003    Meer Mehta     kavya.rao3@example.com  9.310475e+09       Sales
3   1005  Sachin Joshi  sachin.joshi5@example.com  9.152289e+09  Operations
4   1006   Vikas Joshi   vikas.joshi6@example.com  9.775118e+08   Marketing

In [26]:
cs = cs.replace(1, np.nan).ffill()
print(cs)

    EmpID         EmpName                         Email         Phone  \
0    1001     Rohit Yadav      rohit.yadav1@example.com  9.111268e+09
1    1002      Meer Mehta      meera.mehta2@example.com  9.150787e+09
2    1003      Meer Mehta        kavya.rao3@example.com  9.310475e+09
3    1005    Sachin Joshi     sachin.joshi5@example.com  9.152289e+09
4    1006     Vikas Joshi      vikas.joshi6@example.com  9.775118e+08
5    1008       Rahul Rao        rahul.rao8@example.com  9.918615e+09
6    1009      Nitin Iyer       nitin.iyer9@example.com  9.407051e+09
7    1010     Sachin Shah     sachin.shah10@example.com  9.553605e+09
8    1013      Neha Reddy      neha.reddy13@example.com  9.240042e+09
9    1015      Neha Reddy    manoj.kapoor15@example.com  9.240042e+09
10   1016     Amit Sharma     amit.sharma16@example.com  9.688355e+09
11   1018     Deepak Shah     deepak.shah18@example.com  9.731236e+09
12   1020      Nitin Khan      nitin.khan20@example.com  9.899424e+09
13   1021      Nitin Khan     karan.yadav21@example.com  9.737537e+09
14   1022      Sachin Das      sachin.das22@example.com  9.666161e+09
15   1023      Amit Yadav      amit.yadav23@example.com  9.980491e+09
16   1024    Arjun Mishra    arjun.mishra24@example.com  9.203299e+09
17   1025       Meera Das       meera.das25@example.com  9.203299e+09
18   1029  Priya Kulkarni  priya.kulkarni29@example.com  9.631158e+09
19   1030    Rohit Mishra    rohit.mishra30@example.com  9.130307e+09
20   1031    Rohit Mishra     arjun.yadav31@example.com  9.998462e+09
21   1032     Nitin Mehta     nitin.mehta32@example.com  9.803409e+09
22   1033      Ritika Rao      ritika.rao33@example.com  9.172254e+09
23   1034     Nitin Gupta     nitin.gupta34@example.com  9.200346e+09
24   1035     Nitin Gupta     nitin.gupta34@example.com  9.200346e+09
25   1036     Nitin Gupta     nitin.gupta34@example.com  9.200346e+09

    Department
0        Sales
1   Operations
2        Sales
3   Operations
4    Marketing
5        Sales
6    Marketing
7           HR
8           IT
9           HR
10          HR
11       Sales
12          HR
13   Marketing
14          IT
15  Operations
16          HR
17          IT
18          IT
19   Marketing
20   Marketing
21   Marketing
22          HR
23          IT
24          IT
25          IT

In [27]:
cs = cs.replace(1, np.nan).bfill()
print(cs)

    EmpID         EmpName                         Email         Phone  \
0    1001     Rohit Yadav      rohit.yadav1@example.com  9.111268e+09
1    1002      Meer Mehta      meera.mehta2@example.com  9.150787e+09
2    1003      Meer Mehta        kavya.rao3@example.com  9.310475e+09
3    1005    Sachin Joshi     sachin.joshi5@example.com  9.152289e+09
4    1006     Vikas Joshi      vikas.joshi6@example.com  9.775118e+08
5    1008       Rahul Rao        rahul.rao8@example.com  9.918615e+09
6    1009      Nitin Iyer       nitin.iyer9@example.com  9.407051e+09
7    1010     Sachin Shah     sachin.shah10@example.com  9.553605e+09
8    1013      Neha Reddy      neha.reddy13@example.com  9.240042e+09
9    1015      Neha Reddy    manoj.kapoor15@example.com  9.240042e+09
10   1016     Amit Sharma     amit.sharma16@example.com  9.688355e+09
11   1018     Deepak Shah     deepak.shah18@example.com  9.731236e+09
12   1020      Nitin Khan      nitin.khan20@example.com  9.899424e+09
13   1021      Nitin Khan     karan.yadav21@example.com  9.737537e+09
14   1022      Sachin Das      sachin.das22@example.com  9.666161e+09
15   1023      Amit Yadav      amit.yadav23@example.com  9.980491e+09
16   1024    Arjun Mishra    arjun.mishra24@example.com  9.203299e+09
17   1025       Meera Das       meera.das25@example.com  9.203299e+09
18   1029  Priya Kulkarni  priya.kulkarni29@example.com  9.631158e+09
19   1030    Rohit Mishra    rohit.mishra30@example.com  9.130307e+09
20   1031    Rohit Mishra     arjun.yadav31@example.com  9.998462e+09
21   1032     Nitin Mehta     nitin.mehta32@example.com  9.803409e+09
22   1033      Ritika Rao      ritika.rao33@example.com  9.172254e+09
23   1034     Nitin Gupta     nitin.gupta34@example.com  9.200346e+09
24   1035     Nitin Gupta     nitin.gupta34@example.com  9.200346e+09
25   1036     Nitin Gupta     nitin.gupta34@example.com  9.200346e+09

    Department
0        Sales
1   Operations
2        Sales
3   Operations
4    Marketing
5        Sales
6    Marketing
7           HR
8           IT
9           HR
10          HR
11       Sales
12          HR
13   Marketing
14          IT
15  Operations
16          HR
17          IT
18          IT
19   Marketing
20   Marketing
21   Marketing
22          HR
23          IT
24          IT
25          IT