In [ ]:
#Sorting

In [1]:
import pandas as pd

data = {
    "Name": ["Nitu", "Rahul", "Priya", "Amit", "Sneha", "Nitu"],
    "Age": [24, 28, 26, 31, 29, 24],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [35000, 45000, 40000, 60000, 48000, 35000],
    "City": ["Pune", "Mumbai", "Pune", "Delhi", "Mumbai", "Pune"],
    "Joining_Date": [
        "2024-01-15",
        "2022-06-10",
        "2023-03-20",
        "2019-08-12",
        "2021-11-05",
        "2024-01-15"
    ]
}

df = pd.DataFrame(data)
df

    Name  Age Department  Salary    City Joining_Date
0   Nitu   24         IT   35000    Pune   2024-01-15
1  Rahul   28         HR   45000  Mumbai   2022-06-10
2  Priya   26         IT   40000    Pune   2023-03-20
3   Amit   31    Finance   60000   Delhi   2019-08-12
4  Sneha   29         HR   48000  Mumbai   2021-11-05
5   Nitu   24         IT   35000    Pune   2024-01-15

In [2]:
#Q1. Sort employees by Salary from lowest to highest.
df.sort_values("Salary")

    Name  Age Department  Salary    City Joining_Date
0   Nitu   24         IT   35000    Pune   2024-01-15
5   Nitu   24         IT   35000    Pune   2024-01-15
2  Priya   26         IT   40000    Pune   2023-03-20
1  Rahul   28         HR   45000  Mumbai   2022-06-10
4  Sneha   29         HR   48000  Mumbai   2021-11-05
3   Amit   31    Finance   60000   Delhi   2019-08-12

In [3]:
#Q2. Sort employees by Salary from highest to lowest.
df.sort_values("Salary", ascending=False)

    Name  Age Department  Salary    City Joining_Date
3   Amit   31    Finance   60000   Delhi   2019-08-12
4  Sneha   29         HR   48000  Mumbai   2021-11-05
1  Rahul   28         HR   45000  Mumbai   2022-06-10
2  Priya   26         IT   40000    Pune   2023-03-20
0   Nitu   24         IT   35000    Pune   2024-01-15
5   Nitu   24         IT   35000    Pune   2024-01-15

In [4]:
#Q3. Sort employees by Age.
df.sort_values("Age")

    Name  Age Department  Salary    City Joining_Date
0   Nitu   24         IT   35000    Pune   2024-01-15
5   Nitu   24         IT   35000    Pune   2024-01-15
2  Priya   26         IT   40000    Pune   2023-03-20
1  Rahul   28         HR   45000  Mumbai   2022-06-10
4  Sneha   29         HR   48000  Mumbai   2021-11-05
3   Amit   31    Finance   60000   Delhi   2019-08-12

In [5]:
#Q4. Sort employees by Department and then Salary.
df.sort_values(["Department", "Salary"])

    Name  Age Department  Salary    City Joining_Date
3   Amit   31    Finance   60000   Delhi   2019-08-12
1  Rahul   28         HR   45000  Mumbai   2022-06-10
4  Sneha   29         HR   48000  Mumbai   2021-11-05
0   Nitu   24         IT   35000    Pune   2024-01-15
5   Nitu   24         IT   35000    Pune   2024-01-15
2  Priya   26         IT   40000    Pune   2023-03-20

In [ ]:
#Q5. Sort the DataFrame by index.
df.sort_index()

    Name  Age Department  Salary    City Joining_Date
0   Nitu   24         IT   35000    Pune   2024-01-15
1  Rahul   28         HR   45000  Mumbai   2022-06-10
2  Priya   26         IT   40000    Pune   2023-03-20
3   Amit   31    Finance   60000   Delhi   2019-08-12
4  Sneha   29         HR   48000  Mumbai   2021-11-05
5   Nitu   24         IT   35000    Pune   2024-01-15