In [16]:
#String Functions

In [17]:
import pandas as pd

data = {
    "Name": ["Nitu", "Rahul", "Priya", "Amit", "Sneha", "Nitu"],
    "Age": [24, 28, 26, 31, 29, 24],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [35000, 45000, 40000, 60000, 48000, 35000],
    "City": ["Pune", "Mumbai", "Pune", "Delhi", "Mumbai", "Pune"],
    "Joining_Date": [
        "2024-01-15",
        "2022-06-10",
        "2023-03-20",
        "2019-08-12",
        "2021-11-05",
        "2024-01-15"
    ]
}

df = pd.DataFrame(data)
df

    Name  Age Department  Salary    City Joining_Date
0   Nitu   24         IT   35000    Pune   2024-01-15
1  Rahul   28         HR   45000  Mumbai   2022-06-10
2  Priya   26         IT   40000    Pune   2023-03-20
3   Amit   31    Finance   60000   Delhi   2019-08-12
4  Sneha   29         HR   48000  Mumbai   2021-11-05
5   Nitu   24         IT   35000    Pune   2024-01-15

In [18]:
#Q1. Convert all City names to uppercase.
df["City"] = df["City"].str.upper()
df

    Name  Age Department  Salary    City Joining_Date
0   Nitu   24         IT   35000    PUNE   2024-01-15
1  Rahul   28         HR   45000  MUMBAI   2022-06-10
2  Priya   26         IT   40000    PUNE   2023-03-20
3   Amit   31    Finance   60000   DELHI   2019-08-12
4  Sneha   29         HR   48000  MUMBAI   2021-11-05
5   Nitu   24         IT   35000    PUNE   2024-01-15

In [19]:
#Q2. Convert all employees names to lowercase.
df["Name"] = df["Name"].str.lower()
df

    Name  Age Department  Salary    City Joining_Date
0   nitu   24         IT   35000    PUNE   2024-01-15
1  rahul   28         HR   45000  MUMBAI   2022-06-10
2  priya   26         IT   40000    PUNE   2023-03-20
3   amit   31    Finance   60000   DELHI   2019-08-12
4  sneha   29         HR   48000  MUMBAI   2021-11-05
5   nitu   24         IT   35000    PUNE   2024-01-15

In [20]:
#Q3. Find employees whose name contains "i".
df[df["Name"].str.contains("i", case=False)]

    Name  Age Department  Salary   City Joining_Date
0   nitu   24         IT   35000   PUNE   2024-01-15
2  priya   26         IT   40000   PUNE   2023-03-20
3   amit   31    Finance   60000  DELHI   2019-08-12
5   nitu   24         IT   35000   PUNE   2024-01-15

In [21]:
#Q4. Find employees whose city contains "Pune".
df[df["City"].str.contains("Pune", case=False)]
df

    Name  Age Department  Salary    City Joining_Date
0   nitu   24         IT   35000    PUNE   2024-01-15
1  rahul   28         HR   45000  MUMBAI   2022-06-10
2  priya   26         IT   40000    PUNE   2023-03-20
3   amit   31    Finance   60000   DELHI   2019-08-12
4  sneha   29         HR   48000  MUMBAI   2021-11-05
5   nitu   24         IT   35000    PUNE   2024-01-15

In [22]:
#Q5. Find the length of each employee's name.
df["Name_Length"] = df["Name"].str.len()
df

    Name  Age Department  Salary    City Joining_Date  Name_Length
0   nitu   24         IT   35000    PUNE   2024-01-15            4
1  rahul   28         HR   45000  MUMBAI   2022-06-10            5
2  priya   26         IT   40000    PUNE   2023-03-20            5
3   amit   31    Finance   60000   DELHI   2019-08-12            4
4  sneha   29         HR   48000  MUMBAI   2021-11-05            5
5   nitu   24         IT   35000    PUNE   2024-01-15            4

In [23]:
#Q6. Replace "Pune" with "Mumbai".
df["City"] = df["City"].str.replace("Pune", "Mumbai")
df

    Name  Age Department  Salary    City Joining_Date  Name_Length
0   nitu   24         IT   35000    PUNE   2024-01-15            4
1  rahul   28         HR   45000  MUMBAI   2022-06-10            5
2  priya   26         IT   40000    PUNE   2023-03-20            5
3   amit   31    Finance   60000   DELHI   2019-08-12            4
4  sneha   29         HR   48000  MUMBAI   2021-11-05            5
5   nitu   24         IT   35000    PUNE   2024-01-15            4