In [3]:
#Type Conversion

In [4]:
import pandas as pd

data = {
    "Name": ["Nitu", "Rahul", "Priya", "Amit", "Sneha", "Nitu"],
    "Age": [24, 28, 26, 31, 29, 24],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "IT"],
    "Salary": [35000, 45000, 40000, 60000, 48000, 35000],
    "City": ["Pune", "Mumbai", "Pune", "Delhi", "Mumbai", "Pune"],
    "Joining_Date": [
        "2024-01-15",
        "2022-06-10",
        "2023-03-20",
        "2019-08-12",
        "2021-11-05",
        "2024-01-15"
    ]
}

df = pd.DataFrame(data)
df

    Name  Age Department  Salary    City Joining_Date
0   Nitu   24         IT   35000    Pune   2024-01-15
1  Rahul   28         HR   45000  Mumbai   2022-06-10
2  Priya   26         IT   40000    Pune   2023-03-20
3   Amit   31    Finance   60000   Delhi   2019-08-12
4  Sneha   29         HR   48000  Mumbai   2021-11-05
5   Nitu   24         IT   35000    Pune   2024-01-15

In [5]:
#Q1. Check the data types of all columns.
df.dtypes

Name              str
Age             int64
Department        str
Salary          int64
City              str
Joining_Date      str
dtype: object

In [11]:
#Q2. Convert Age to float.
df["Age"] = df["Age"].astype(float)
df

    Name   Age Department   Salary    City Joining_Date
0   Nitu  24.0         IT  35000.0    Pune   2024-01-15
1  Rahul  28.0         HR  45000.0  Mumbai   2022-06-10
2  Priya  26.0         IT  40000.0    Pune   2023-03-20
3   Amit  31.0    Finance  60000.0   Delhi   2019-08-12
4  Sneha  29.0         HR  48000.0  Mumbai   2021-11-05
5   Nitu  24.0         IT  35000.0    Pune   2024-01-15

In [13]:
#Q3. Convert Salary to float.
df["Salary"] = df["Salary"].astype(float)
df

    Name   Age Department   Salary    City Joining_Date
0   Nitu  24.0         IT  35000.0    Pune   2024-01-15
1  Rahul  28.0         HR  45000.0  Mumbai   2022-06-10
2  Priya  26.0         IT  40000.0    Pune   2023-03-20
3   Amit  31.0    Finance  60000.0   Delhi   2019-08-12
4  Sneha  29.0         HR  48000.0  Mumbai   2021-11-05
5   Nitu  24.0         IT  35000.0    Pune   2024-01-15

In [14]:
#Q4. Convert Joining_Date from object/string to datetime.
df["Joining_Date"] = pd.to_datetime(df["Joining_Date"])
df

    Name   Age Department   Salary    City Joining_Date
0   Nitu  24.0         IT  35000.0    Pune   2024-01-15
1  Rahul  28.0         HR  45000.0  Mumbai   2022-06-10
2  Priya  26.0         IT  40000.0    Pune   2023-03-20
3   Amit  31.0    Finance  60000.0   Delhi   2019-08-12
4  Sneha  29.0         HR  48000.0  Mumbai   2021-11-05
5   Nitu  24.0         IT  35000.0    Pune   2024-01-15

In [9]:
#Q5. Check the data types again.
df.dtypes

Name                       str
Age                    float64
Department                 str
Salary                 float64
City                       str
Joining_Date    datetime64[us]
dtype: object